-- Generated by npm run db:branch-upgrade. Requires base migrations 0001-0020.
BEGIN;
DO $$ BEGIN IF to_regclass('public.branches') IS NULL THEN RAISE EXCEPTION 'Database belum memiliki cabang. Pilih cabang pemilik data lama.'; END IF; END $$;
-- supabase/migrations/0021_incremental_sync.sql
-- Transactional change cursor. No business row contents are stored here.

CREATE TABLE IF NOT EXISTS public.printex_sync_clock (
 singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton), revision bigint NOT NULL DEFAULT 0
);
INSERT INTO public.printex_sync_clock(singleton) VALUES(true) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS public.printex_row_changes (
 table_name text NOT NULL, row_id uuid NOT NULL, branch_key text NOT NULL DEFAULT '',
 revision bigint NOT NULL, deleted boolean NOT NULL,
 PRIMARY KEY(table_name,row_id,branch_key)
);
CREATE INDEX IF NOT EXISTS printex_changes_revision ON public.printex_row_changes(revision);
ALTER TABLE public.printex_sync_clock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.printex_row_changes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.printex_sync_clock,public.printex_row_changes FROM PUBLIC,anon,authenticated;
CREATE OR REPLACE FUNCTION public.printex_record_change() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE rev bigint; item jsonb; prior jsonb;
BEGIN
 -- The row lock is held until commit: cursors cannot skip a late-committing transaction.
 UPDATE public.printex_sync_clock SET revision=revision+1 WHERE singleton RETURNING revision INTO rev;
 item := CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
 IF TG_OP='UPDATE' THEN
  prior := to_jsonb(OLD);
  IF prior->>'branch_id' IS DISTINCT FROM item->>'branch_id' THEN
   INSERT INTO public.printex_row_changes VALUES(TG_TABLE_NAME,(prior->>'id')::uuid,coalesce(prior->>'branch_id',''),rev,true)
   ON CONFLICT(table_name,row_id,branch_key) DO UPDATE SET revision=EXCLUDED.revision,deleted=true;
  END IF;
 END IF;
 INSERT INTO public.printex_row_changes VALUES(TG_TABLE_NAME,(item->>'id')::uuid,coalesce(item->>'branch_id',''),rev,TG_OP='DELETE')
 ON CONFLICT(table_name,row_id,branch_key) DO UPDATE SET revision=EXCLUDED.revision,deleted=EXCLUDED.deleted;
 RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION public.printex_record_change() FROM PUBLIC,anon,authenticated;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['orders','customers','production_steps','process_history'] LOOP
  EXECUTE format('DROP TRIGGER IF EXISTS printex_track_change ON public.%I',t);
  EXECUTE format('CREATE TRIGGER printex_track_change AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.printex_record_change()',t);
 END LOOP;
END $$;
CREATE OR REPLACE FUNCTION public.printex_sync_changes(p_after bigint DEFAULT NULL,p_branch uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE permitted boolean; branch_mode boolean; result jsonb;
BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 branch_mode := to_regclass('public.branches') IS NOT NULL;
 IF branch_mode THEN
  IF p_branch IS NULL THEN EXECUTE 'SELECT public.printex_central_owner()' INTO permitted;
  ELSE EXECUTE 'SELECT public.printex_branch_access($1)' INTO permitted USING p_branch; END IF;
  IF NOT permitted THEN RAISE EXCEPTION 'Cabang tidak dapat diakses' USING ERRCODE='42501'; END IF;
 END IF;
 -- Clock and changes are read in ONE statement/snapshot. Return only IDs, never row contents.
 WITH delta AS (
  SELECT d.table_name,d.row_id FROM public.printex_row_changes d
  WHERE p_after IS NOT NULL AND d.revision>p_after
   AND (NOT branch_mode OR p_branch IS NULL OR d.branch_key=p_branch::text OR d.table_name='production_steps')
  LIMIT 2001
 ), summary AS (SELECT count(*) AS n FROM delta)
 SELECT jsonb_build_object('cursor',c.revision::text,'reset',summary.n>2000,'changes',
  CASE WHEN p_after IS NULL OR summary.n>2000 THEN '[]'::jsonb
  ELSE coalesce((SELECT jsonb_agg(jsonb_build_object('table',d.table_name,'id',d.row_id)) FROM delta d),'[]'::jsonb) END)
 INTO result FROM public.printex_sync_clock c CROSS JOIN summary WHERE singleton;
 RETURN result;
END $$;
REVOKE ALL ON FUNCTION public.printex_sync_changes(bigint,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_sync_changes(bigint,uuid) TO authenticated;

-- supabase/branch-migrations/0001_branches.sql
-- Production branch migration. Apply in order after base migrations.

-- Seed the initial branches only on first installation. An upgrade must not
-- recreate a branch that the central owner has deliberately deleted.
DO $$ BEGIN
 IF to_regclass('public.branches') IS NULL THEN
CREATE TABLE public.branches (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, is_active boolean NOT NULL DEFAULT true
);
INSERT INTO public.branches(id,name) VALUES
('11111111-1111-4111-8111-111111111111','Salatiga'),
('22222222-2222-4222-8222-222222222222','Semarang') ON CONFLICT DO NOTHING;
 END IF;
END $$;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES public.branches(id);
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK(role IN ('central_owner','owner','admin','operator'));
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES public.branches(id);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES public.branches(id);
ALTER TABLE public.process_history ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES public.branches(id);
ALTER TABLE public.order_photo_cleanup ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES public.branches(id);
DO $$ DECLARE selected uuid; BEGIN
 IF EXISTS(SELECT 1 FROM public.orders WHERE branch_id IS NULL)
 OR EXISTS(SELECT 1 FROM public.profiles WHERE branch_id IS NULL AND role<>'central_owner') THEN
   SELECT id INTO selected FROM public.branches WHERE name=current_setting('printex.legacy_branch',true);
   IF selected IS NULL THEN RAISE EXCEPTION 'Pilih cabang data lama: SET printex.legacy_branch = Salatiga atau Semarang'; END IF;
   -- Branch metadata backfill must not rewrite archive dates or increment versions.
   ALTER TABLE public.orders DISABLE TRIGGER USER;
   UPDATE public.orders SET branch_id=selected WHERE branch_id IS NULL;
   ALTER TABLE public.orders ENABLE TRIGGER USER;
   UPDATE public.customers SET branch_id=selected WHERE branch_id IS NULL;
   UPDATE public.process_history SET branch_id=selected WHERE branch_id IS NULL;
   UPDATE public.profiles SET branch_id=selected WHERE branch_id IS NULL AND role<>'central_owner';
   UPDATE public.order_photo_cleanup SET branch_id=selected WHERE branch_id IS NULL;
 END IF;
END $$;
ALTER TABLE public.orders ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE public.customers ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE public.process_history ALTER COLUMN branch_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS orders_branch_created ON public.orders(branch_id,created_at);
CREATE INDEX IF NOT EXISTS customers_branch ON public.customers(branch_id);
CREATE INDEX IF NOT EXISTS history_branch_time ON public.process_history(branch_id,occurred_at);
CREATE OR REPLACE FUNCTION public.printex_staff() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_active AND role IN ('central_owner','owner','admin','operator'));
$$;
CREATE OR REPLACE FUNCTION public.printex_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_active AND role IN ('central_owner','owner','admin'));
$$;
CREATE OR REPLACE FUNCTION public.printex_central_owner() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_active AND role='central_owner');
$$;
CREATE OR REPLACE FUNCTION public.printex_branch_access(p_branch uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.profiles p WHERE p.id=auth.uid() AND p.is_active
 AND (p.role='central_owner' OR (p.branch_id=p_branch AND p.role IN ('owner','admin','operator'))))
 AND EXISTS(SELECT 1 FROM public.branches WHERE id=p_branch AND is_active);
$$;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.branches FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.branches TO authenticated;
DROP POLICY IF EXISTS branches_read ON public.branches;
CREATE POLICY branches_read ON public.branches FOR SELECT TO authenticated USING(public.printex_branch_access(id));
DO $$ DECLARE t text; p record; BEGIN
 FOREACH t IN ARRAY ARRAY['orders','customers','process_history'] LOOP
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename=t LOOP
   EXECUTE format('DROP POLICY %I ON public.%I',p.policyname,t);
  END LOOP;
  EXECUTE format('CREATE POLICY branch_read ON public.%I FOR SELECT TO authenticated USING(public.printex_branch_access(branch_id))',t);
 END LOOP;
 -- Legacy tables are not used by the board. Keep them private to the central owner
 -- until their workflows acquire explicit branch membership.
 FOREACH t IN ARRAY ARRAY['machines','order_step_events','order_activities','production_schedules','schedule_items'] LOOP
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename=t LOOP
   EXECUTE format('DROP POLICY %I ON public.%I',p.policyname,t);
  END LOOP;
  EXECUTE format('CREATE POLICY central_read ON public.%I FOR SELECT TO authenticated USING(public.printex_central_owner())',t);
 END LOOP;
END $$;
DROP POLICY IF EXISTS online_read ON public.profiles;
CREATE POLICY online_read ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.printex_central_owner());
CREATE OR REPLACE FUNCTION public.printex_history_branch() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 SELECT branch_id INTO NEW.branch_id FROM public.orders WHERE id=NEW.order_id;
 IF NEW.branch_id IS NULL THEN RAISE EXCEPTION 'Cabang riwayat tidak ditemukan'; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS history_branch ON public.process_history;
CREATE TRIGGER history_branch BEFORE INSERT ON public.process_history FOR EACH ROW EXECUTE FUNCTION public.printex_history_branch();
CREATE OR REPLACE FUNCTION public.printex_mutate_order(p_action text, p_order_id uuid, p_expected_version bigint, p_data jsonb DEFAULT '{}')
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE o public.orders; customer_uuid uuid; stage_uuid uuid; result_id uuid; actor_role text; source_code text; selected_branch uuid;
BEGIN
  -- Lock the authenticated profile until commit, including against concurrent role changes.
  SELECT p.role INTO actor_role FROM public.profiles p
    WHERE p.id=auth.uid() AND p.is_active AND p.role IN ('central_owner','owner','admin','operator') FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Akun belum diberi akses oleh admin' USING ERRCODE='42501'; END IF;
  IF p_action IS NULL OR p_action NOT IN ('create','edit','move','delete','archive','finish') THEN RAISE EXCEPTION 'Aksi tidak valid'; END IF;
  IF actor_role='operator' AND p_action<>'move' THEN
    RAISE EXCEPTION 'Operator tidak dapat menambah, mengedit, menghapus, atau mengarsipkan order' USING ERRCODE='42501';
  END IF;
  IF p_action IN ('create','edit') THEN
    IF length(trim(p_data->>'customerPhone')) > 30 THEN
      RAISE EXCEPTION 'Nomor WhatsApp maksimal 30 karakter';
    END IF;
    IF nullif(trim(p_data->>'customerName'),'') IS NULL OR length(p_data->>'customerName') > 200
       OR (p_data->>'productionType') NOT IN ('Sublim','DTF','Umbul-umbul','Batik','Jersey')
       OR p_data->>'productionType' IS NULL OR (p_data->>'meter')::numeric < 0
       OR (p_data->>'meter') IS NULL OR (p_data->>'customerType') NOT IN ('regular','priority')
       OR p_data->>'customerType' IS NULL OR nullif(p_data->>'orderDate','') IS NULL OR nullif(p_data->>'dueDate','') IS NULL THEN
      RAISE EXCEPTION 'Data order tidak lengkap atau tidak valid';
    END IF;
  END IF;
  IF p_action = 'create' THEN
    -- Client-generated UUID makes retry after a lost response idempotent.
    PERFORM pg_advisory_xact_lock(hashtextextended(p_order_id::text,0));
    IF EXISTS(SELECT 1 FROM public.orders WHERE id=p_order_id) THEN
      IF NOT EXISTS(SELECT 1 FROM public.orders WHERE id=p_order_id AND public.printex_branch_access(branch_id)) THEN
        RAISE EXCEPTION 'Order tidak tersedia untuk cabang Anda' USING ERRCODE='42501';
      END IF;
      RETURN p_order_id;
    END IF;
    selected_branch:=nullif(p_data->>'branchId','')::uuid;
    IF selected_branch IS NULL THEN SELECT branch_id INTO selected_branch FROM public.profiles WHERE id=auth.uid(); END IF;
    IF NOT public.printex_branch_access(selected_branch) THEN RAISE EXCEPTION 'Pilih cabang yang dapat Anda akses' USING ERRCODE='42501'; END IF;
    INSERT INTO public.customers(branch_id,name,phone) VALUES(selected_branch,trim(p_data->>'customerName'),nullif(trim(p_data->>'customerPhone'),'')) RETURNING id INTO customer_uuid;
    INSERT INTO public.orders(branch_id,id,spk_code,customer_id,production_type,meter,customer_type,order_date,due_at,notes,created_by)
    VALUES(selected_branch,p_order_id,'SPK-'||nextval('public.printex_spk_seq'),customer_uuid,p_data->>'productionType',
      (p_data->>'meter')::numeric,p_data->>'customerType',(p_data->>'orderDate')::date,(p_data->>'dueDate')::date,
      COALESCE(p_data->>'notes',''),auth.uid()) RETURNING id INTO result_id;
    RETURN result_id;
  END IF;
  SELECT * INTO o FROM public.orders WHERE id=p_order_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Order sudah dihapus atau tidak ditemukan'; END IF;
  IF NOT public.printex_branch_access(o.branch_id) THEN RAISE EXCEPTION 'Order tidak tersedia untuk cabang Anda' USING ERRCODE='42501'; END IF;
  IF actor_role='operator' THEN
    SELECT code INTO source_code FROM public.production_steps WHERE id=o.current_step_id;
    IF source_code IS NULL OR source_code NOT IN ('DESIGN_DONE','PRINTING','PRESS','DONE')
      OR COALESCE(p_data->>'code','') NOT IN ('DESIGN_DONE','PRINTING','PRESS','DONE') THEN
      RAISE EXCEPTION 'Operator hanya dapat memindahkan order antara Menunggu Pembayaran, Sublim, Press, dan Order Selesai' USING ERRCODE='42501';
    END IF;
  END IF;
  IF p_action='finish' AND o.archive_finalized_at IS NOT NULL THEN RETURN o.id; END IF;
  IF o.version IS DISTINCT FROM p_expected_version THEN RAISE EXCEPTION 'Order sudah diubah perangkat lain. Muat ulang dan coba lagi.' USING ERRCODE='40001'; END IF;
  CASE p_action
  WHEN 'edit' THEN
    IF nullif(trim(p_data->>'spkCode'),'') IS NULL THEN RAISE EXCEPTION 'Kode SPK wajib diisi'; END IF;
    UPDATE public.customers SET name=trim(p_data->>'customerName'),phone=CASE WHEN p_data ? 'customerPhone' THEN nullif(trim(p_data->>'customerPhone'),'') ELSE phone END,updated_at=statement_timestamp() WHERE id=o.customer_id;
    UPDATE public.orders SET spk_code=trim(p_data->>'spkCode'),production_type=p_data->>'productionType',meter=(p_data->>'meter')::numeric,
      customer_type=p_data->>'customerType',order_date=(p_data->>'orderDate')::date,due_at=(p_data->>'dueDate')::date,notes=COALESCE(p_data->>'notes','') WHERE id=o.id;
  WHEN 'move' THEN
    IF p_data->>'code' = 'ARCHIVE' THEN RAISE EXCEPTION 'Konfirmasi penyerahan sebelum arsip'; END IF;
    SELECT id INTO STRICT stage_uuid FROM public.production_steps WHERE code=p_data->>'code';
    UPDATE public.orders SET current_step_id=stage_uuid WHERE id=o.id;
  WHEN 'archive' THEN
    SELECT id INTO STRICT stage_uuid FROM public.production_steps WHERE code='ARCHIVE';
    UPDATE public.orders SET current_step_id=stage_uuid,delivery_method=p_data->>'deliveryMethod' WHERE id=o.id;
  WHEN 'finish' THEN
    UPDATE public.orders SET archive_finalized_at=statement_timestamp() WHERE id=o.id;
  WHEN 'delete' THEN
    DELETE FROM public.orders WHERE id=o.id;
  END CASE;
  RETURN o.id;
END $$;
CREATE OR REPLACE FUNCTION public.printex_set_order_photo(p_order_id uuid,p_expected_version bigint,p_path text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE o public.orders;
BEGIN
  PERFORM 1 FROM public.profiles WHERE id=auth.uid() AND is_active AND role IN ('central_owner','owner','admin') FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Hanya Owner/Admin yang dapat mengubah foto order' USING ERRCODE='42501'; END IF;
  IF p_path IS NOT NULL THEN
    PERFORM pg_advisory_xact_lock(hashtextextended(p_path,16));
    IF EXISTS(SELECT 1 FROM public.order_photo_cleanup WHERE path=p_path AND claimed) THEN
      RAISE EXCEPTION 'Foto sudah dijadwalkan untuk dibersihkan. Unggah ulang foto.';
    END IF;
  END IF;
  SELECT * INTO o FROM public.orders WHERE id=p_order_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Order tidak ditemukan'; END IF;
  IF NOT public.printex_branch_access(o.branch_id) THEN RAISE EXCEPTION 'Foto tidak tersedia untuk cabang Anda' USING ERRCODE='42501'; END IF;
  IF o.archived_at IS NOT NULL THEN RAISE EXCEPTION 'Foto order arsip tidak dapat diubah'; END IF;
  IF o.photo_path IS NOT DISTINCT FROM p_path THEN RETURN; END IF;
  IF o.version IS DISTINCT FROM p_expected_version THEN
    RAISE EXCEPTION 'Order sudah diubah perangkat lain. Muat ulang dan coba lagi.' USING ERRCODE='40001';
  END IF;
  IF p_path IS NOT NULL THEN
    IF p_path !~ ('^'||p_order_id::text||'/[0-9a-f-]{36}\.(jpg|png|webp)$') THEN RAISE EXCEPTION 'Lokasi foto tidak valid'; END IF;
    PERFORM 1 FROM storage.objects WHERE bucket_id='order-photos' AND name=p_path FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Foto belum diunggah'; END IF;
  END IF;
  UPDATE public.orders SET photo_path=p_path WHERE id=p_order_id;
  DELETE FROM public.order_photo_cleanup WHERE path=p_path AND NOT claimed;
END $$;
REVOKE ALL ON FUNCTION public.printex_set_order_photo(uuid,bigint,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_set_order_photo(uuid,bigint,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.printex_queue_old_photo() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF OLD.photo_path IS NOT NULL AND (TG_OP='DELETE' OR OLD.photo_path IS DISTINCT FROM NEW.photo_path) THEN
  INSERT INTO public.order_photo_cleanup(path,branch_id) VALUES(OLD.photo_path,OLD.branch_id) ON CONFLICT(path) DO UPDATE SET branch_id=EXCLUDED.branch_id;
 END IF;
 RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION public.printex_photo_branch_access(p_path text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.orders WHERE id::text=split_part(p_path,'/',1) AND public.printex_branch_access(branch_id))
 OR EXISTS(SELECT 1 FROM public.order_photo_cleanup WHERE path=p_path AND public.printex_branch_access(branch_id));
$$;
DROP POLICY IF EXISTS order_photos_read ON storage.objects;
CREATE POLICY order_photos_read ON storage.objects FOR SELECT TO authenticated USING(bucket_id='order-photos' AND public.printex_photo_branch_access(name));
DROP POLICY IF EXISTS order_photos_upload ON storage.objects;
CREATE POLICY order_photos_upload ON storage.objects FOR INSERT TO authenticated WITH CHECK(
 bucket_id='order-photos' AND public.printex_admin() AND name ~ '^[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|png|webp)$'
 AND EXISTS(SELECT 1 FROM public.orders WHERE id::text=split_part(name,'/',1) AND archived_at IS NULL AND public.printex_branch_access(branch_id)));
CREATE OR REPLACE FUNCTION public.printex_claim_photo_cleanup(p_path text DEFAULT NULL)
RETURNS TABLE(path text) LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE candidate text;
BEGIN
  IF NOT public.printex_admin() THEN RAISE EXCEPTION 'Hanya Owner/Admin dapat membersihkan foto' USING ERRCODE='42501'; END IF;
  -- A missing object after a successful API deletion needs no remaining queue row.
  DELETE FROM public.order_photo_cleanup q WHERE q.queued_at < now()-interval '1 day'
    AND NOT EXISTS(SELECT 1 FROM storage.objects s WHERE s.bucket_id='order-photos' AND public.printex_photo_branch_access(s.name) AND s.name=q.path);
  FOR candidate IN
    SELECT s.name FROM storage.objects s
    WHERE s.bucket_id='order-photos' AND public.printex_photo_branch_access(s.name)
      AND (CASE WHEN p_path IS NOT NULL THEN s.name=p_path ELSE
        s.created_at < now()-interval '24 hours' OR EXISTS(SELECT 1 FROM public.order_photo_cleanup q WHERE q.path=s.name) END)
      AND NOT EXISTS(SELECT 1 FROM public.orders o WHERE o.photo_path=s.name)
    ORDER BY s.created_at,s.name LIMIT 50
  LOOP
    -- The photo-link RPC takes the same lock. After this claim it cannot attach the path.
    PERFORM pg_advisory_xact_lock(hashtextextended(candidate,16));
    IF NOT EXISTS(SELECT 1 FROM public.orders o WHERE o.photo_path=candidate) THEN
      INSERT INTO public.order_photo_cleanup AS q(path,claimed,branch_id)
      VALUES(candidate,true,(SELECT branch_id FROM public.orders WHERE id::text=split_part(candidate,'/',1)))
        ON CONFLICT ON CONSTRAINT order_photo_cleanup_pkey DO UPDATE SET claimed=true;
      path:=candidate; RETURN NEXT;
    END IF;
  END LOOP;
END $$;
REVOKE ALL ON FUNCTION public.printex_claim_photo_cleanup(text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_claim_photo_cleanup(text) TO authenticated;

CREATE OR REPLACE FUNCTION public.printex_photo_deletable(p_path text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
  SELECT public.printex_admin() AND public.printex_photo_branch_access(p_path)
    AND EXISTS(SELECT 1 FROM public.order_photo_cleanup q WHERE q.path=p_path AND q.claimed)
    AND NOT EXISTS(SELECT 1 FROM public.orders o WHERE o.photo_path=p_path);
$$;
REVOKE ALL ON FUNCTION public.printex_photo_deletable(text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_photo_deletable(text) TO authenticated;
DROP POLICY IF EXISTS order_photos_delete ON storage.objects;
CREATE POLICY order_photos_delete ON storage.objects FOR DELETE TO authenticated
USING (bucket_id='order-photos' AND public.printex_photo_deletable(name));


CREATE OR REPLACE FUNCTION public.printex_branch_context() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 RETURN jsonb_build_object('branches',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) ORDER BY name),'[]') FROM public.branches WHERE public.printex_branch_access(id)),
 'central',public.printex_central_owner(),'branchId',(SELECT branch_id FROM public.profiles WHERE id=auth.uid()));
END $$;
-- Central management is intentionally required in this pilot.
CREATE OR REPLACE FUNCTION public.printex_list_users() RETURNS TABLE(id uuid,email text,full_name text,role text,is_active boolean)
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT public.printex_central_owner() THEN RAISE EXCEPTION 'Hanya Owner Pusat yang dapat mengelola akun' USING ERRCODE='42501'; END IF;
 RETURN QUERY SELECT p.id,u.email::text,p.full_name,p.role,p.is_active FROM public.profiles p JOIN auth.users u ON u.id=p.id WHERE u.deleted_at IS NULL;
END $$;
CREATE OR REPLACE FUNCTION public.printex_manage_user(p_id uuid,p_name text,p_role text,p_active boolean,p_delete boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE target public.profiles;
BEGIN
  -- Serialize role changes so concurrent removals cannot remove the last Owner.
  PERFORM pg_advisory_xact_lock(hashtextextended('printex-user-management',0));
  IF NOT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND is_active AND role='central_owner') THEN
    RAISE EXCEPTION 'Hanya Owner yang dapat mengelola akun' USING ERRCODE='42501';
  END IF;
  SELECT * INTO target FROM public.profiles WHERE id=p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Akun tidak ditemukan'; END IF;
  IF p_id=auth.uid() AND (p_delete OR p_active IS DISTINCT FROM true OR p_role IS DISTINCT FROM 'central_owner') THEN
    RAISE EXCEPTION 'Tidak dapat menghapus, menonaktifkan, atau menurunkan role akun sendiri';
  END IF;
  IF target.role='central_owner' AND target.is_active AND (p_delete OR p_active IS DISTINCT FROM true OR p_role IS DISTINCT FROM 'central_owner')
    AND NOT EXISTS(SELECT 1 FROM public.profiles WHERE role='central_owner' AND is_active AND id<>p_id) THEN
    RAISE EXCEPTION 'Minimal satu Owner aktif harus tersedia';
  END IF;
  IF p_delete THEN
    UPDATE public.profiles SET is_active=false,deletion_requested_at=now(),updated_at=now() WHERE id=p_id;
  ELSE
    IF target.deletion_requested_at IS NOT NULL THEN RAISE EXCEPTION 'Penghapusan akun sedang diproses. Selesaikan penghapusan terlebih dahulu'; END IF;
    IF nullif(trim(p_name),'') IS NULL OR length(p_name)>100 OR p_role IS NULL OR p_role NOT IN ('central_owner','owner','admin','operator') OR p_active IS NULL THEN
      RAISE EXCEPTION 'Nama, role, atau status akun tidak valid';
    END IF;
    IF EXISTS(SELECT 1 FROM auth.users WHERE id=p_id AND deleted_at IS NOT NULL) THEN RAISE EXCEPTION 'Akun sudah dihapus'; END IF;
    UPDATE public.profiles SET full_name=trim(p_name),role=p_role,is_active=p_active,updated_at=now() WHERE id=p_id;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.printex_assign_branch(p_user uuid,p_branch uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT public.printex_central_owner() THEN RAISE EXCEPTION 'Hanya Owner Pusat' USING ERRCODE='42501'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.branches WHERE id=p_branch AND is_active) THEN RAISE EXCEPTION 'Cabang tidak valid'; END IF;
 UPDATE public.profiles SET branch_id=p_branch WHERE id=p_user;
 IF NOT FOUND THEN RAISE EXCEPTION 'Akun tidak ditemukan'; END IF;
END $$;
REVOKE ALL ON FUNCTION public.printex_central_owner(),public.printex_branch_access(uuid),
public.printex_photo_branch_access(text),public.printex_branch_context(),public.printex_assign_branch(uuid,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_central_owner(),public.printex_branch_access(uuid),
public.printex_photo_branch_access(text),public.printex_branch_context(),public.printex_assign_branch(uuid,uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.printex_online_status() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 RETURN jsonb_build_object('schema_version',8,'branches_enabled',true,'realtime_tables',
 (SELECT jsonb_agg(tablename) FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public'));
END $$;

CREATE OR REPLACE FUNCTION public.printex_manage_branch_user(p_id uuid,p_name text,p_role text,p_active boolean,p_branch uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT public.printex_central_owner() THEN RAISE EXCEPTION 'Hanya Owner Pusat' USING ERRCODE='42501'; END IF;
 IF p_role<>'central_owner' THEN
   IF p_branch IS NULL THEN RAISE EXCEPTION 'Pilih cabang akun'; END IF;
   PERFORM public.printex_assign_branch(p_id,p_branch);
 END IF;
 PERFORM public.printex_manage_user(p_id,p_name,p_role,p_active,false);
END $$;
REVOKE ALL ON FUNCTION public.printex_manage_branch_user(uuid,text,text,boolean,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_manage_branch_user(uuid,text,text,boolean,uuid) TO authenticated;

-- supabase/branch-migrations/0002_branch_users.sql
-- Production branch migration. Apply in order after base migrations.

CREATE OR REPLACE FUNCTION public.printex_branch_manages_user(p_target uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.profiles actor JOIN public.profiles target ON target.id=p_target
 WHERE actor.id=auth.uid() AND actor.is_active AND actor.role='owner'
 AND actor.branch_id=target.branch_id AND target.role IN ('admin','operator')
 AND public.printex_branch_access(actor.branch_id));
$$;
REVOKE ALL ON FUNCTION public.printex_branch_manages_user(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_branch_manages_user(uuid) TO authenticated;
DROP POLICY IF EXISTS online_read ON public.profiles;
CREATE POLICY online_read ON public.profiles FOR SELECT TO authenticated
USING(id=auth.uid() OR public.printex_central_owner() OR public.printex_branch_manages_user(id));

CREATE OR REPLACE FUNCTION public.printex_list_users() RETURNS TABLE(id uuid,email text,full_name text,role text,is_active boolean)
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM public.profiles actor WHERE actor.id=auth.uid() AND actor.is_active AND actor.role IN ('central_owner','owner'))
 THEN RAISE EXCEPTION 'Hanya Owner yang dapat mengelola akun' USING ERRCODE='42501'; END IF;
 RETURN QUERY SELECT p.id,u.email::text,p.full_name,p.role,p.is_active
 FROM public.profiles p JOIN auth.users u ON u.id=p.id
 WHERE (u.deleted_at IS NULL OR p.deletion_requested_at IS NOT NULL)
 AND (public.printex_central_owner() OR public.printex_branch_manages_user(p.id));
END $$;
CREATE OR REPLACE FUNCTION public.printex_manage_user(p_id uuid,p_name text,p_role text,p_active boolean,p_delete boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE target public.profiles; actor public.profiles;
BEGIN
  -- Serialize role changes so concurrent removals cannot remove the last Owner.
  PERFORM pg_advisory_xact_lock(hashtextextended('printex-user-management',0));
  SELECT * INTO actor FROM public.profiles WHERE id=auth.uid() AND is_active AND role IN ('central_owner','owner') FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Hanya Owner yang dapat mengelola akun' USING ERRCODE='42501'; END IF;
  SELECT * INTO target FROM public.profiles WHERE id=p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Akun tidak ditemukan'; END IF;
  IF actor.role='owner' AND (
    actor.branch_id IS NULL OR target.branch_id IS DISTINCT FROM actor.branch_id
    OR target.role NOT IN ('admin','operator')
    OR (NOT p_delete AND (p_role IS NULL OR p_role NOT IN ('admin','operator')))
    OR NOT public.printex_branch_access(actor.branch_id)
  ) THEN RAISE EXCEPTION 'Owner Cabang hanya mengelola Admin dan Operator cabangnya' USING ERRCODE='42501'; END IF;

  IF p_id=auth.uid() AND (p_delete OR p_active IS DISTINCT FROM true OR p_role IS DISTINCT FROM 'central_owner') THEN
    RAISE EXCEPTION 'Tidak dapat menghapus, menonaktifkan, atau menurunkan role akun sendiri';
  END IF;
  IF target.role='central_owner' AND target.is_active AND (p_delete OR p_active IS DISTINCT FROM true OR p_role IS DISTINCT FROM 'central_owner')
    AND NOT EXISTS(SELECT 1 FROM public.profiles WHERE role='central_owner' AND is_active AND id<>p_id) THEN
    RAISE EXCEPTION 'Minimal satu Owner aktif harus tersedia';
  END IF;
  IF p_delete THEN
    UPDATE public.profiles SET is_active=false,deletion_requested_at=now(),updated_at=now() WHERE id=p_id;
  ELSE
    IF target.deletion_requested_at IS NOT NULL THEN RAISE EXCEPTION 'Penghapusan akun sedang diproses. Selesaikan penghapusan terlebih dahulu'; END IF;
    IF nullif(trim(p_name),'') IS NULL OR length(p_name)>100 OR p_role IS NULL OR p_role NOT IN ('central_owner','owner','admin','operator') OR p_active IS NULL THEN
      RAISE EXCEPTION 'Nama, role, atau status akun tidak valid';
    END IF;
    IF EXISTS(SELECT 1 FROM auth.users WHERE id=p_id AND deleted_at IS NOT NULL) THEN RAISE EXCEPTION 'Akun sudah dihapus'; END IF;
    UPDATE public.profiles SET full_name=trim(p_name),role=p_role,is_active=p_active,updated_at=now() WHERE id=p_id;
  END IF;
END $$;


CREATE OR REPLACE FUNCTION public.printex_manage_branch_user(p_id uuid,p_name text,p_role text,p_active boolean,p_branch uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE actor public.profiles; target public.profiles;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended('printex-user-management',0));
 SELECT * INTO actor FROM public.profiles WHERE id=auth.uid() AND is_active AND role IN ('central_owner','owner') FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Hanya Owner yang dapat mengelola akun' USING ERRCODE='42501'; END IF;
 SELECT * INTO target FROM public.profiles WHERE id=p_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Akun tidak ditemukan'; END IF;
 IF actor.role='central_owner' THEN
   IF p_role<>'central_owner' THEN
     IF p_branch IS NULL THEN RAISE EXCEPTION 'Pilih cabang akun'; END IF;
     PERFORM public.printex_assign_branch(p_id,p_branch);
   END IF;
 ELSE
   IF p_role IS NULL OR p_role NOT IN ('admin','operator') OR p_branch IS DISTINCT FROM actor.branch_id
     OR NOT public.printex_branch_access(actor.branch_id) THEN
     RAISE EXCEPTION 'Owner Cabang hanya mengelola Admin dan Operator cabangnya' USING ERRCODE='42501';
   END IF;
   -- Only a new inactive profile created by this owner's server action can be assigned.
   -- raw_app_meta_data cannot be forged by client-side Auth updates.
   IF target.branch_id IS NULL AND NOT target.is_active AND target.role='operator'
     AND EXISTS(SELECT 1 FROM auth.users WHERE id=p_id
       AND raw_app_meta_data->>'provisioned_by'=auth.uid()::text
       AND raw_app_meta_data->>'provisioned_branch'=actor.branch_id::text) THEN
     UPDATE public.profiles SET branch_id=actor.branch_id WHERE id=p_id;
   ELSIF target.branch_id IS DISTINCT FROM actor.branch_id OR target.role NOT IN ('admin','operator') THEN
     RAISE EXCEPTION 'Akun di luar hak kelola cabang' USING ERRCODE='42501';
   END IF;
 END IF;
 PERFORM public.printex_manage_user(p_id,p_name,p_role,p_active,false);
END $$;
REVOKE ALL ON FUNCTION public.printex_manage_branch_user(uuid,text,text,boolean,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_manage_branch_user(uuid,text,text,boolean,uuid) TO authenticated;

-- supabase/branch-migrations/0003_branch_settings.sql
-- Production branch migration. Apply in order after base migrations.

CREATE TABLE IF NOT EXISTS public.branch_customer_service_settings (
 branch_id uuid PRIMARY KEY REFERENCES public.branches(id),
 whatsapp_number text NOT NULL DEFAULT '' CHECK (whatsapp_number='' OR whatsapp_number ~ '^[1-9][0-9]{7,14}$')
);
CREATE TABLE IF NOT EXISTS public.branch_stock_shortcuts (
 branch_id uuid NOT NULL REFERENCES public.branches(id),
 id text NOT NULL CHECK (id IN ('dtf_paper','fabric')),
 label text NOT NULL CHECK (length(trim(label)) BETWEEN 1 AND 60),
 url text NOT NULL DEFAULT '' CHECK (url='' OR (length(url)<=2048 AND url ~ '^https://[^[:space:]]+$')),
 version bigint NOT NULL DEFAULT 1 CHECK (version>0),
 PRIMARY KEY(branch_id,id)
);
CREATE OR REPLACE FUNCTION public.printex_initialize_branch_settings() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 INSERT INTO public.branch_customer_service_settings(branch_id) VALUES(NEW.id) ON CONFLICT DO NOTHING;
 INSERT INTO public.branch_stock_shortcuts(branch_id,id,label) VALUES
 (NEW.id,'dtf_paper','Stock DTF dan Kertas'),(NEW.id,'fabric','Stock Kain') ON CONFLICT DO NOTHING;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.printex_initialize_branch_settings() FROM PUBLIC,anon,authenticated;
DROP TRIGGER IF EXISTS initialize_branch_settings ON public.branches;
CREATE TRIGGER initialize_branch_settings AFTER INSERT ON public.branches FOR EACH ROW EXECUTE FUNCTION public.printex_initialize_branch_settings();
INSERT INTO public.branch_customer_service_settings(branch_id) SELECT id FROM public.branches ON CONFLICT DO NOTHING;
INSERT INTO public.branch_stock_shortcuts(branch_id,id,label)
 SELECT b.id,s.id,s.label FROM public.branches b CROSS JOIN
 (VALUES ('dtf_paper','Stock DTF dan Kertas'),('fabric','Stock Kain')) s(id,label) ON CONFLICT DO NOTHING;
ALTER TABLE public.branch_customer_service_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_stock_shortcuts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.branch_customer_service_settings,public.branch_stock_shortcuts FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.branch_customer_service_settings,public.branch_stock_shortcuts TO authenticated;
GRANT UPDATE(whatsapp_number) ON public.branch_customer_service_settings TO authenticated;
GRANT UPDATE(label,url,version) ON public.branch_stock_shortcuts TO authenticated;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['branch_customer_service_settings','branch_stock_shortcuts'] LOOP
 EXECUTE format('DROP POLICY IF EXISTS branch_settings_read ON public.%I',t);
 EXECUTE format('CREATE POLICY branch_settings_read ON public.%I FOR SELECT TO authenticated USING(public.printex_branch_access(branch_id))',t);
 EXECUTE format('DROP POLICY IF EXISTS branch_settings_write ON public.%I',t);
 EXECUTE format('CREATE POLICY branch_settings_write ON public.%I FOR UPDATE TO authenticated USING(public.printex_branch_access(branch_id) AND public.printex_admin()) WITH CHECK(public.printex_branch_access(branch_id) AND public.printex_admin())',t);
 END LOOP;
END $$;
-- Block the former shared endpoints, including direct requests from old clients.
REVOKE ALL ON public.customer_service_settings,public.stock_shortcuts FROM authenticated,anon;

-- supabase/branch-migrations/0004_capabilities.sql

CREATE OR REPLACE FUNCTION public.printex_online_status() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 RETURN jsonb_build_object('schema_version',8,'branches_enabled',true,'branch_settings_enabled',true,'incremental_sync_enabled',true,'branch_schema_version',4,'realtime_tables',
 (SELECT jsonb_agg(tablename) FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public'));
END $$;

-- supabase/branch-migrations/0005_shared_customer_service.sql
-- One support team for all branches. Preserve existing shared contact and legacy branch rows.

INSERT INTO public.customer_service_settings(singleton) VALUES(true) ON CONFLICT DO NOTHING;
-- Keep the former shared number. Branch-specific numbers are not chosen automatically.
ALTER TABLE public.customer_service_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.customer_service_settings FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.customer_service_settings TO authenticated;
GRANT UPDATE(whatsapp_number) ON public.customer_service_settings TO authenticated;
DROP POLICY IF EXISTS customer_service_read ON public.customer_service_settings;
CREATE POLICY customer_service_read ON public.customer_service_settings FOR SELECT TO authenticated USING(public.printex_staff());
DROP POLICY IF EXISTS customer_service_update ON public.customer_service_settings;
CREATE POLICY customer_service_update ON public.customer_service_settings FOR UPDATE TO authenticated
 USING(public.printex_admin()) WITH CHECK(public.printex_admin());
REVOKE ALL ON public.branch_customer_service_settings FROM PUBLIC,anon,authenticated;
CREATE OR REPLACE FUNCTION public.printex_initialize_branch_settings() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 INSERT INTO public.branch_stock_shortcuts(branch_id,id,label) VALUES
 (NEW.id,'dtf_paper','Stock DTF dan Kertas'),(NEW.id,'fabric','Stock Kain') ON CONFLICT DO NOTHING;
 RETURN NEW;
END $$;

-- supabase/branch-migrations/0006_paper_width.sql
-- Apply after existing order migrations; supports single-branch and branch RPCs.

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS paper_width numeric;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.orders'::regclass AND conname='orders_paper_width_check') THEN
  ALTER TABLE public.orders ADD CONSTRAINT orders_paper_width_check CHECK(paper_width IS NULL OR (production_type='Sublim' AND paper_width IN (1.2,1.6,1.8)));
 END IF;
END $$;
DO $migration$
DECLARE definition text;
BEGIN
 SELECT pg_get_functiondef('public.printex_mutate_order(text,uuid,bigint,jsonb)'::regprocedure) INTO definition;
 IF position('paperWidth' IN definition)=0 THEN
  IF position('production_type,meter,customer_type' IN definition)=0 OR position('meter=(p_data->>''meter'')::numeric,' IN definition)=0 THEN
   RAISE EXCEPTION 'Versi RPC tidak dikenali. Jalankan migrasi order sebelumnya.';
  END IF;
  definition := replace(definition, 'IF p_action IN (''create'',''edit'') THEN',
   'IF p_action IN (''create'',''edit'') THEN
    IF p_data ? ''paperWidth'' AND p_data->>''paperWidth'' IS NOT NULL AND
      ((p_data->>''paperWidth'') NOT IN (''1.2'',''1.6'',''1.8'') OR p_data->>''productionType'' <> ''Sublim'') THEN
      RAISE EXCEPTION ''Lebar kertas hanya untuk Sublim: pilih 1,2, 1,6, atau 1,8 meter'';
    END IF;');
  definition := replace(definition,'production_type,meter,customer_type','production_type,meter,paper_width,customer_type');
  definition := replace(definition,'(p_data->>''meter'')::numeric,p_data->>''customerType''','(p_data->>''meter'')::numeric,(p_data->>''paperWidth'')::numeric,p_data->>''customerType''');
  definition := replace(definition,'meter=(p_data->>''meter'')::numeric,',
   'meter=(p_data->>''meter'')::numeric,paper_width=CASE WHEN p_data->>''productionType''<>''Sublim'' THEN NULL WHEN p_data ? ''paperWidth'' THEN (p_data->>''paperWidth'')::numeric ELSE o.paper_width END,');
  EXECUTE definition;
 END IF;
END $migration$;

-- supabase/branch-migrations/0007_non_dtf_paper_width.sql
-- All non-DTF production uses sublimation paper. Run after paper width migration.

ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_paper_width_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_paper_width_check
 CHECK(paper_width IS NULL OR (production_type='DTF' AND paper_width=0.6) OR (production_type<>'DTF' AND paper_width IN (1.2,1.6,1.8)));
DO $migration$
DECLARE definition text;
BEGIN
 SELECT pg_get_functiondef('public.printex_mutate_order(text,uuid,bigint,jsonb)'::regprocedure) INTO definition;
 IF position('paperWidth' IN definition)=0 THEN RAISE EXCEPTION 'Jalankan migrasi lebar kertas sebelumnya terlebih dahulu.'; END IF;
 definition := replace(definition, 'p_data->>''productionType'' <> ''Sublim''', 'p_data->>''productionType'' = ''DTF''');
 definition := replace(definition, 'p_data->>''productionType''<>''Sublim''', 'p_data->>''productionType''=''DTF''');
 definition := replace(definition, 'Lebar kertas hanya untuk Sublim:', 'Lebar kertas untuk semua produksi selain DTF:');
 EXECUTE definition;
END $migration$;

-- supabase/branch-migrations/0008_branch_management.sql
-- Branch lifecycle within the existing project. Files are removed via Storage API.

CREATE TABLE IF NOT EXISTS public.branch_deletions (
 branch_id uuid PRIMARY KEY REFERENCES public.branches(id),
 photo_paths jsonb NOT NULL DEFAULT '[]', user_ids jsonb NOT NULL DEFAULT '[]'
);
ALTER TABLE public.branch_deletions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.branch_deletions FROM PUBLIC,anon,authenticated;

-- Serialize new writes with branch retirement. Existing profile deactivation remains possible.
CREATE OR REPLACE FUNCTION public.printex_require_active_branch() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NEW.branch_id IS NULL THEN RETURN NEW; END IF;
 IF TG_TABLE_NAME='profiles' AND TG_OP='UPDATE' THEN
   IF NEW.branch_id IS NOT DISTINCT FROM OLD.branch_id AND NOT NEW.is_active THEN RETURN NEW; END IF;
 END IF;
 PERFORM 1 FROM public.branches WHERE id=NEW.branch_id AND is_active FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Cabang tidak aktif atau sedang dihapus'; END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.printex_require_active_branch() FROM PUBLIC,anon,authenticated;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['orders','customers','profiles'] LOOP
  EXECUTE format('DROP TRIGGER IF EXISTS require_active_branch ON public.%I',t);
  EXECUTE format('CREATE TRIGGER require_active_branch BEFORE INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.printex_require_active_branch()',t);
 END LOOP;
END $$;

-- An upload already in flight must finish before retirement, or fail afterward.
CREATE OR REPLACE FUNCTION public.printex_upload_active_branch() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE branch uuid;
BEGIN
 IF NEW.bucket_id <> 'order-photos' THEN RETURN NEW; END IF;
 SELECT branch_id INTO branch FROM public.orders WHERE id::text=split_part(NEW.name,'/',1);
 IF branch IS NULL THEN RAISE EXCEPTION 'Order foto tidak ditemukan'; END IF;
 IF branch IS NOT NULL THEN
  PERFORM 1 FROM public.branches WHERE id=branch AND is_active FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Cabang tidak aktif atau sedang dihapus'; END IF;
 END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.printex_upload_active_branch() FROM PUBLIC,anon,authenticated;
DROP TRIGGER IF EXISTS printex_upload_active_branch ON storage.objects;
CREATE TRIGGER printex_upload_active_branch BEFORE INSERT OR UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.printex_upload_active_branch();

CREATE OR REPLACE FUNCTION public.printex_manage_branch(p_action text,p_id uuid DEFAULT NULL,p_name text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE b public.branches; job public.branch_deletions;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended('printex-user-management',0));
 PERFORM 1 FROM public.profiles WHERE id=auth.uid() AND is_active AND role='central_owner' FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Hanya Owner Pusat yang dapat mengelola cabang' USING ERRCODE='42501'; END IF;
 IF p_action='list' THEN
  RETURN (SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'deleting',EXISTS(SELECT 1 FROM public.branch_deletions d WHERE d.branch_id=branches.id)) ORDER BY name),'[]') FROM public.branches);
 END IF;
 IF p_action NOT IN ('create','rename','prepare_delete','finish_delete') OR p_action IS NULL OR p_id IS NULL THEN RAISE EXCEPTION 'Aksi cabang tidak valid'; END IF;
 IF p_action IN ('create','rename') AND (p_name IS NULL OR length(trim(p_name)) NOT BETWEEN 1 AND 100) THEN RAISE EXCEPTION 'Nama cabang harus 1?100 karakter'; END IF;
 IF p_action='create' THEN
  IF EXISTS(SELECT 1 FROM public.branches WHERE id=p_id AND name=trim(p_name) AND is_active) THEN RETURN '{}'::jsonb; END IF;
  IF EXISTS(SELECT 1 FROM public.branches WHERE lower(name)=lower(trim(p_name))) THEN RAISE EXCEPTION 'Nama cabang sudah digunakan'; END IF;
  INSERT INTO public.branches(id,name) VALUES(p_id,trim(p_name));
  RETURN '{}'::jsonb;
 END IF;
 SELECT * INTO b FROM public.branches WHERE id=p_id FOR UPDATE;
 IF NOT FOUND THEN
  IF p_action IN ('prepare_delete','finish_delete') THEN RETURN jsonb_build_object('photo_paths','[]'::jsonb,'user_ids','[]'::jsonb); END IF;
  RAISE EXCEPTION 'Cabang tidak ditemukan';
 END IF;
 IF p_action='rename' THEN
  IF NOT b.is_active THEN RAISE EXCEPTION 'Cabang sedang dihapus'; END IF;
  IF EXISTS(SELECT 1 FROM public.branches WHERE id<>p_id AND lower(name)=lower(trim(p_name))) THEN RAISE EXCEPTION 'Nama cabang sudah digunakan'; END IF;
  UPDATE public.branches SET name=trim(p_name) WHERE id=p_id;
  RETURN '{}'::jsonb;
 END IF;
 IF p_name IS DISTINCT FROM b.name THEN RAISE EXCEPTION 'Nama konfirmasi tidak cocok. Muat ulang daftar cabang'; END IF;
 SELECT * INTO job FROM public.branch_deletions WHERE branch_id=p_id;
 IF p_action='prepare_delete' THEN
  IF job.branch_id IS NULL THEN
   INSERT INTO public.branch_deletions(branch_id,photo_paths,user_ids)
   SELECT p_id,
    (SELECT coalesce(jsonb_agg(s.name),'[]') FROM storage.objects s WHERE s.bucket_id='order-photos' AND (
      EXISTS(SELECT 1 FROM public.orders o WHERE o.branch_id=p_id AND (o.id::text=split_part(s.name,'/',1) OR o.photo_path=s.name))
      OR EXISTS(SELECT 1 FROM public.order_photo_cleanup q WHERE q.branch_id=p_id AND q.path=s.name))),
    (SELECT coalesce(jsonb_agg(id),'[]') FROM public.profiles WHERE branch_id=p_id AND role<>'central_owner')
   RETURNING * INTO job;
   UPDATE public.profiles SET branch_id=NULL WHERE branch_id=p_id AND role='central_owner';
   UPDATE public.profiles SET is_active=false,deletion_requested_at=now() WHERE branch_id=p_id;
   UPDATE public.branches SET is_active=false WHERE id=p_id;
   -- Remove order references before Auth deletion invokes profile FK SET NULL actions.
   -- The durable manifest retains every file and account required for cleanup retries.
   DELETE FROM public.production_schedules ps
    WHERE EXISTS(SELECT 1 FROM public.schedule_items si JOIN public.orders o ON o.id=si.order_id WHERE si.schedule_id=ps.id AND o.branch_id=p_id)
    AND NOT EXISTS(SELECT 1 FROM public.schedule_items si JOIN public.orders o ON o.id=si.order_id WHERE si.schedule_id=ps.id AND o.branch_id<>p_id);
   DELETE FROM public.schedule_items WHERE order_id IN (SELECT id FROM public.orders WHERE branch_id=p_id);
   DELETE FROM public.process_history WHERE branch_id=p_id;
   DELETE FROM public.orders WHERE branch_id=p_id;
   DELETE FROM public.customers WHERE branch_id=p_id;
  END IF;
  RETURN jsonb_build_object('photo_paths',job.photo_paths,'user_ids',job.user_ids);
 END IF;
 IF job.branch_id IS NULL THEN RAISE EXCEPTION 'Mulai penghapusan cabang terlebih dahulu'; END IF;
 IF EXISTS(SELECT 1 FROM storage.objects s WHERE s.bucket_id='order-photos' AND job.photo_paths ? s.name) THEN RAISE EXCEPTION 'File cabang belum selesai dihapus. Coba lagi'; END IF;
 IF EXISTS(SELECT 1 FROM auth.users u WHERE job.user_ids ? u.id::text) THEN RAISE EXCEPTION 'Akun cabang belum selesai dihapus. Coba lagi'; END IF;
 DELETE FROM public.schedule_items WHERE order_id IN (SELECT id FROM public.orders WHERE branch_id=p_id);
 DELETE FROM public.process_history WHERE branch_id=p_id;
 DELETE FROM public.orders WHERE branch_id=p_id;
 DELETE FROM public.customers WHERE branch_id=p_id;
 DELETE FROM public.order_photo_cleanup WHERE branch_id=p_id OR job.photo_paths ? path;
 DELETE FROM public.branch_customer_service_settings WHERE branch_id=p_id;
 DELETE FROM public.branch_stock_shortcuts WHERE branch_id=p_id;
 -- Keep sync tombstones so other central-owner devices remove cached branch rows.
 DELETE FROM public.branch_deletions WHERE branch_id=p_id;
 DELETE FROM public.branches WHERE id=p_id;
 RETURN '{}'::jsonb;
END $$;
REVOKE ALL ON FUNCTION public.printex_manage_branch(text,uuid,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_manage_branch(text,uuid,text) TO authenticated;

-- supabase/branch-migrations/0009_archive_branch_deletion.sql
-- Requires 0008. Preserve normal archive protection while deleting retired branches.

CREATE OR REPLACE FUNCTION public.enforce_order_archiving()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE previous_code text; next_code text;
BEGIN
  -- Archived rows may only be removed as part of a verified central-owner
  -- branch retirement. Normal order deletion must still preserve archives.
  IF TG_OP = 'DELETE' THEN
    IF public.printex_central_owner() AND EXISTS (
      SELECT 1 FROM public.branch_deletions d JOIN public.branches b ON b.id=d.branch_id
      WHERE d.branch_id=OLD.branch_id AND NOT b.is_active
    ) THEN RETURN OLD; END IF;
  END IF;
  -- Only FK-triggered removal of user references may update finalized archives.
  IF TG_OP = 'UPDATE' AND pg_trigger_depth() > 1 THEN
    IF (to_jsonb(NEW) - 'created_by' - 'assigned_designer_id' - 'updated_at' - 'version')
      = (to_jsonb(OLD) - 'created_by' - 'assigned_designer_id' - 'updated_at' - 'version')
      AND (NEW.created_by IS NULL OR NEW.created_by IS NOT DISTINCT FROM OLD.created_by)
      AND (NEW.assigned_designer_id IS NULL OR NEW.assigned_designer_id IS NOT DISTINCT FROM OLD.assigned_designer_id) THEN
      RETURN NEW;
    END IF;
  END IF;
  IF current_setting('printex.importing',true) = 'yes' THEN RETURN NEW; END IF;
  IF TG_OP <> 'INSERT' THEN
    SELECT code INTO previous_code FROM public.production_steps WHERE id = OLD.current_step_id;
    IF previous_code = 'ARCHIVE' THEN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Preserve archived orders and reports';
      END IF;
      IF (to_jsonb(NEW) - 'archive_finalized_at' - 'updated_at' - 'version')
         IS DISTINCT FROM (to_jsonb(OLD) - 'archive_finalized_at' - 'updated_at' - 'version') THEN
        RAISE EXCEPTION 'Archived order data is read-only';
      END IF;
      IF OLD.archive_finalized_at IS NOT NULL THEN
        RETURN OLD; -- repeated clicks cannot change the original report date
      END IF;
      IF NEW.archive_finalized_at IS NOT NULL THEN
        IF OLD.archived_at IS NULL OR OLD.delivery_method IS NULL THEN
          RAISE EXCEPTION 'Delivery confirmation is required before finalization';
        END IF;
        NEW.archive_finalized_at := statement_timestamp();
        NEW.photo_path := NULL; -- Release the photo only when leaving the board for reports.
      END IF;
      RETURN NEW;
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  IF NEW.archive_finalized_at IS NOT NULL THEN
    RAISE EXCEPTION 'Move to the archive board before finalizing';
  END IF;
  SELECT code INTO next_code FROM public.production_steps WHERE id = NEW.current_step_id;
  IF next_code = 'ARCHIVE' THEN
    IF TG_OP = 'INSERT' OR previous_code IS DISTINCT FROM 'DONE' THEN
      RAISE EXCEPTION 'Only Done orders can be archived';
    END IF;
    IF NEW.delivery_method IS NULL OR NEW.delivery_method NOT IN ('pickup', 'delivery') THEN
      RAISE EXCEPTION 'Confirm pickup or delivery before archiving';
    END IF;
    NEW.archived_at := statement_timestamp();
    NEW.order_state := 'completed';
  ELSIF NEW.archived_at IS NOT NULL OR NEW.delivery_method IS NOT NULL THEN
    RAISE EXCEPTION 'Delivery metadata is only valid for archived orders';
  END IF;
  RETURN NEW;
END;
$$;

-- supabase/branch-migrations/0010_dtf_paper_width.sql
-- DTF uses 0.6 m automatically; other production uses 1.2 / 1.6 / 1.8 m.

ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_paper_width_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_paper_width_check
 CHECK(paper_width IS NULL OR (production_type='DTF' AND paper_width=0.6) OR (production_type<>'DTF' AND paper_width IN (1.2,1.6,1.8)));
DO $migration$
DECLARE definition text;
BEGIN
 SELECT pg_get_functiondef('public.printex_mutate_order(text,uuid,bigint,jsonb)'::regprocedure) INTO definition;
 IF position('paperWidth' IN definition)=0 THEN RAISE EXCEPTION 'Jalankan migrasi lebar kertas sebelumnya terlebih dahulu.'; END IF;
 IF position('-- automatic DTF paper' IN definition)=0 THEN
  definition := replace(definition, 'IF p_action IN (''create'',''edit'') THEN',
   'IF p_action IN (''create'',''edit'') THEN
    -- automatic DTF paper
    IF p_data->>''productionType'' = ''DTF'' THEN
      p_data := jsonb_set(p_data, ''{paperWidth}'', ''"0.6"''::jsonb);
    END IF;');
 END IF;
 definition := replace(definition,
  '((p_data->>''paperWidth'') NOT IN (''1.2'',''1.6'',''1.8'') OR p_data->>''productionType'' = ''DTF'')',
  '(p_data->>''productionType'' <> ''DTF'' AND (p_data->>''paperWidth'') NOT IN (''1.2'',''1.6'',''1.8''))');
 definition := replace(definition, 'WHEN p_data->>''productionType''=''DTF'' THEN NULL', 'WHEN p_data->>''productionType''=''DTF'' THEN 0.6');
 IF position('ELSE CASE WHEN o.paper_width=0.6' IN definition)=0 THEN
 definition := replace(definition, 'ELSE o.paper_width END', 'ELSE CASE WHEN o.paper_width=0.6 THEN NULL ELSE o.paper_width END END');
 END IF;
 EXECUTE definition;
END $migration$;

-- supabase/branch-migrations/0011_snapshot_indexes.sql
-- allRows uses WHERE branch_id = ? [AND id > ?] ORDER BY id LIMIT 1000.
-- Existing branch/date indexes cannot provide that ordering. Primary keys still
-- serve all-branch reads and incremental WHERE id IN (...) lookups.
CREATE INDEX IF NOT EXISTS orders_branch_id_page ON public.orders(branch_id,id);
CREATE INDEX IF NOT EXISTS customers_branch_id_page ON public.customers(branch_id,id);
CREATE INDEX IF NOT EXISTS history_branch_id_page ON public.process_history(branch_id,id);

-- supabase/migrations/0025_scoped_snapshot.sql
-- Load active production plus only the orders needed by the selected period.
-- Keep each selected order's complete history so revisits and original milestones
-- retain their existing reporting semantics. RLS applies to every source table.

CREATE INDEX IF NOT EXISTS orders_finalized_at_scope ON public.orders(archive_finalized_at);
CREATE INDEX IF NOT EXISTS orders_order_date_scope ON public.orders(order_date);
CREATE INDEX IF NOT EXISTS process_history_scope_time ON public.process_history(occurred_at,order_identity);
CREATE INDEX IF NOT EXISTS process_history_scope_identity ON public.process_history(order_identity);

DROP FUNCTION IF EXISTS public.printex_scoped_snapshot(date,date,uuid,uuid,jsonb);
DROP FUNCTION IF EXISTS public.printex_scoped_snapshot(date,date,uuid,uuid,jsonb,uuid,boolean,text[]);
CREATE FUNCTION public.printex_scoped_snapshot(
 p_start date, p_end date, p_branch uuid DEFAULT NULL,
 p_order uuid DEFAULT NULL, p_changes jsonb DEFAULT NULL,
 p_history_after uuid DEFAULT NULL,p_history_only boolean DEFAULT false,p_history_ids text[] DEFAULT NULL
) RETURNS json LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path='' AS $$
DECLARE branch_mode boolean; result json; branch_order text; branch_history text; history_branch_field text; history_branch_column text;
BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 IF p_start IS NULL OR p_end IS NULL OR p_end<p_start OR p_end-p_start>365 THEN
  RAISE EXCEPTION 'Rentang data tidak valid';
 END IF;
 branch_mode := to_regclass('public.branches') IS NOT NULL;
 branch_order := CASE WHEN branch_mode THEN ' AND ($3 IS NULL OR o.branch_id=$3)' ELSE '' END;
 branch_history := CASE WHEN branch_mode THEN ' AND ($3 IS NULL OR h.branch_id=$3)' ELSE '' END;
 history_branch_field := CASE WHEN branch_mode THEN ', ''branch_id'',h.branch_id' ELSE '' END;
 history_branch_column := CASE WHEN branch_mode THEN ',h.branch_id' ELSE '' END;
 EXECUTE '
 WITH selected_identity AS MATERIALIZED (
  SELECT unnest($8::text[]) AS identity WHERE $8 IS NOT NULL
  UNION
  SELECT o.id::text AS identity FROM public.orders o WHERE $8 IS NULL AND
   (o.archive_finalized_at IS NULL OR o.order_date BETWEEN $1 AND $2
    OR o.archive_finalized_at >= ($1::timestamp AT TIME ZONE ''Asia/Jakarta'')
       AND o.archive_finalized_at < (($2+1)::timestamp AT TIME ZONE ''Asia/Jakarta'')
    OR o.id=$4)' || branch_order || '
  UNION
  SELECT h.order_identity FROM public.process_history h WHERE $8 IS NULL AND
   h.occurred_at >= ($1::timestamp AT TIME ZONE ''Asia/Jakarta'')
   AND h.occurred_at < (($2+1)::timestamp AT TIME ZONE ''Asia/Jakarta'')' || branch_history || '
 ), selected_orders AS MATERIALIZED (
  SELECT o.id,o.customer_id FROM public.orders o JOIN selected_identity i ON i.identity=o.id::text
  WHERE true' || branch_order || '
 ), changed AS MATERIALIZED (
  SELECT item->>''table'' AS table_name,item->>''id'' AS id
  FROM jsonb_array_elements(coalesce($5,''[]''::jsonb)) item
 ), history_page AS MATERIALIZED (
  SELECT h.id,h.order_identity,h.spk_code,h.step_id,h.event_kind,h.occurred_at,h.actor_name,h.customer_name' || history_branch_column || '
  FROM public.process_history h JOIN selected_identity i ON i.identity=h.order_identity
  WHERE ($6 IS NULL OR h.id>$6)' || branch_history || '
   AND ($5 IS NULL OR EXISTS(SELECT 1 FROM changed c WHERE c.table_name=''process_history'' AND c.id=h.id::text))
  ORDER BY h.id LIMIT 5001
 ), history_rows AS MATERIALIZED (SELECT * FROM history_page ORDER BY id LIMIT 5000)
 SELECT json_build_object(
  ''orders'',CASE WHEN $7 THEN ''[]''::json ELSE coalesce((SELECT json_agg(row_to_json(o)) FROM public.orders o JOIN selected_orders s ON s.id=o.id
   WHERE $5 IS NULL OR EXISTS(SELECT 1 FROM changed c WHERE c.table_name=''orders'' AND c.id=o.id::text)),''[]''::json) END,
  ''customers'',CASE WHEN $7 THEN ''[]''::json ELSE coalesce((SELECT json_agg(json_build_object(''id'',t.id,''name'',t.name,''phone'',t.phone)) FROM public.customers t
   WHERE EXISTS(SELECT 1 FROM selected_orders o WHERE o.customer_id=t.id)
   AND ($5 IS NULL OR EXISTS(SELECT 1 FROM changed c WHERE c.table_name=''customers'' AND c.id=t.id::text))),''[]''::json) END,
  ''production_steps'',CASE WHEN $7 THEN ''[]''::json ELSE coalesce((SELECT json_agg(json_build_object(''id'',t.id,''code'',t.code)) FROM public.production_steps t
   WHERE $5 IS NULL OR EXISTS(SELECT 1 FROM changed c WHERE c.table_name=''production_steps'' AND c.id=t.id::text)),''[]''::json) END,
  ''process_history'',coalesce((SELECT json_agg(json_build_object(
   ''id'',h.id,''order_identity'',h.order_identity,''spk_code'',h.spk_code,''step_id'',h.step_id,
   ''event_kind'',h.event_kind,''occurred_at'',h.occurred_at,''actor_name'',h.actor_name,
   ''customer_name'',h.customer_name' || history_branch_field || ')) FROM history_rows h),''[]''::json),
  ''history_more'',(SELECT count(*)>5000 FROM history_page),
  ''history_cursor'',(SELECT id FROM history_rows ORDER BY id DESC LIMIT 1),
  ''identities'',CASE WHEN $7 THEN ''[]''::json ELSE coalesce((SELECT json_agg(identity) FROM selected_identity),''[]''::json) END
 )' INTO result USING p_start,p_end,p_branch,p_order,p_changes,p_history_after,p_history_only,p_history_ids;
 RETURN result;
END $$;
REVOKE ALL ON FUNCTION public.printex_scoped_snapshot(date,date,uuid,uuid,jsonb,uuid,boolean,text[]) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.printex_scoped_snapshot(date,date,uuid,uuid,jsonb,uuid,boolean,text[]) TO authenticated;

-- supabase/migrations/0026_cached_branch_reads.sql
-- Evaluate the authorized branch set once per read statement, instead of
-- looking up the same profile and branch for each history row.

DO $migration$
DECLARE t text;
BEGIN
 IF to_regclass('public.branches') IS NULL THEN RETURN; END IF;
 EXECUTE $function$
  CREATE OR REPLACE FUNCTION public.printex_read_branches() RETURNS SETOF uuid
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $body$
   SELECT b.id FROM public.branches b JOIN public.profiles p ON p.id=(SELECT auth.uid())
   WHERE b.is_active AND p.is_active
    AND (p.role='central_owner' OR (p.branch_id=b.id AND p.role IN ('owner','admin','operator')))
  $body$
 $function$;
 REVOKE ALL ON FUNCTION public.printex_read_branches() FROM PUBLIC,anon;
 GRANT EXECUTE ON FUNCTION public.printex_read_branches() TO authenticated;
 ALTER POLICY branches_read ON public.branches USING(id IN (SELECT public.printex_read_branches()));
 FOREACH t IN ARRAY ARRAY['orders','customers','process_history'] LOOP
  EXECUTE format('ALTER POLICY branch_read ON public.%I USING(branch_id IN (SELECT public.printex_read_branches()))',t);
 END LOOP;
END $migration$;

-- supabase/migrations/0027_compact_transitions.sql
-- One row per transition; retain the destination for accurate timing/revisions.

ALTER TABLE public.process_history ADD COLUMN IF NOT EXISTS next_step_id uuid REFERENCES public.production_steps(id);
ALTER TABLE public.process_history ADD COLUMN IF NOT EXISTS next_event_id uuid;
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_delivery_method_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_delivery_method_check CHECK(delivery_method IN ('pickup','delivery','received'));

CREATE OR REPLACE FUNCTION public.capture_process_history()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE previous_sequence integer; next_sequence integer; employee_name text; customer text;
BEGIN
 IF current_setting('printex.importing',true)='yes' THEN RETURN NEW; END IF;
 IF TG_OP='UPDATE' AND OLD.current_step_id IS NOT DISTINCT FROM NEW.current_step_id THEN RETURN NEW; END IF;
 IF NEW.current_step_id IS NULL THEN RAISE EXCEPTION 'An existing production stage cannot be cleared'; END IF;
 SELECT sequence INTO STRICT next_sequence FROM public.production_steps WHERE id=NEW.current_step_id;
 SELECT full_name INTO employee_name FROM public.profiles WHERE id=auth.uid();
 SELECT name INTO customer FROM public.customers WHERE id=NEW.customer_id;
 IF TG_OP='UPDATE' AND OLD.current_step_id IS NOT NULL THEN
  SELECT sequence INTO STRICT previous_sequence FROM public.production_steps WHERE id=OLD.current_step_id;
  INSERT INTO public.process_history(order_id,spk_code,step_id,event_kind,actor_id,actor_name,assigned_employee_id,customer_name,next_step_id,next_event_id,occurred_at)
  VALUES(NEW.id,NEW.spk_code,OLD.current_step_id,CASE WHEN next_sequence>previous_sequence THEN 'completed' ELSE 'returned' END,
   auth.uid(),employee_name,OLD.assigned_designer_id,coalesce(customer,''),NEW.current_step_id,gen_random_uuid(),statement_timestamp());
 ELSE
  -- One initial anchor per order, rather than an entry at every stage.
  INSERT INTO public.process_history(order_id,spk_code,step_id,event_kind,actor_id,actor_name,assigned_employee_id,customer_name,occurred_at)
  VALUES(NEW.id,NEW.spk_code,NEW.current_step_id,'entered',auth.uid(),employee_name,NEW.assigned_designer_id,coalesce(customer,''),statement_timestamp());
 END IF;
 RETURN NEW;
END $$;

-- Preserve existing archive protections and branch retirement behavior.
DO $$ DECLARE definition text; BEGIN
 SELECT pg_get_functiondef('public.enforce_order_archiving()'::regprocedure) INTO definition;
 definition:=replace(definition,'''pickup'', ''delivery''','''pickup'', ''delivery'', ''received''');
 definition:=replace(definition,'NEW.archived_at := statement_timestamp();',
  'NEW.archived_at := statement_timestamp(); IF NEW.delivery_method = ''received'' THEN NEW.archive_finalized_at := NEW.archived_at; NEW.photo_path := NULL; END IF;');
 EXECUTE definition;
END $$;

-- Add compact metadata to the scoped response without expanding it on the server.
DO $$ DECLARE definition text; BEGIN
 SELECT pg_get_functiondef('public.printex_scoped_snapshot(date,date,uuid,uuid,jsonb,uuid,boolean,text[])'::regprocedure) INTO definition;
 IF position('h.next_step_id' IN definition)=0 THEN
  definition:=replace(definition,'h.actor_name,h.customer_name','h.actor_name,h.customer_name,h.next_step_id,h.next_event_id');
  definition:=replace(definition,'''customer_name'''',h.customer_name','''customer_name'''',h.customer_name,''''next_step_id'''',h.next_step_id,''''next_event_id'''',h.next_event_id');
  EXECUTE definition;
 END IF;
END $$;
NOTIFY pgrst,'reload schema';

-- supabase/migrations/0028_skip_archive_process_reads.sql
-- Receipt is reported from orders.archive_finalized_at, not a seventh process.
-- Preserve stored history; omit unused archive-stage rows from dashboard reads.

DO $$ DECLARE definition text; BEGIN
 SELECT pg_get_functiondef('public.printex_scoped_snapshot(date,date,uuid,uuid,jsonb,uuid,boolean,text[])'::regprocedure) INTO definition;
 IF position('skip_archive_process' IN definition)=0 THEN
  definition:=replace(definition,'WHERE ($6 IS NULL OR h.id>$6)',
   'WHERE ($6 IS NULL OR h.id>$6) AND h.step_id NOT IN (SELECT id FROM public.production_steps WHERE code=''''ARCHIVE'''') /* skip_archive_process */');
  EXECUTE definition;
 END IF;
END $$;
NOTIFY pgrst,'reload schema';

-- supabase/migrations/0029_manual_spk_on_create.sql
-- Use the manually entered SPK on create; preserve retries and legacy clients.

DO $$ DECLARE definition text; generated text := '''SPK-''||nextval(''public.printex_spk_seq'')'; BEGIN
 SELECT pg_get_functiondef('public.printex_mutate_order(text,uuid,bigint,jsonb)'::regprocedure) INTO definition;
 IF position('manual_spk_on_create' IN definition)=0 THEN
  IF position(generated IN definition)=0 THEN RAISE EXCEPTION 'SPK generator not recognized; refusing function replacement'; END IF;
  definition:=replace(definition,generated,
   'coalesce(nullif(trim(p_data->>''spkCode''),''''),'||generated||') /* manual_spk_on_create */');
  definition:=replace(definition,'IF p_action = ''create'' THEN',
   'IF p_action = ''create'' THEN IF p_data ? ''spkCode'' AND nullif(trim(p_data->>''spkCode''),'''') IS NULL THEN RAISE EXCEPTION ''Kode SPK wajib diisi''; END IF;');
  EXECUTE definition;
 END IF;
END $$;
NOTIFY pgrst,'reload schema';

-- supabase/migrations/0030_history_without_actors.sql
-- Preserve the history API shape; do not store the person performing a move.

CREATE OR REPLACE FUNCTION public.capture_process_history()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE previous_sequence integer; next_sequence integer; customer text;
BEGIN
 IF current_setting('printex.importing',true)='yes' THEN RETURN NEW; END IF;
 IF TG_OP='UPDATE' AND OLD.current_step_id IS NOT DISTINCT FROM NEW.current_step_id THEN RETURN NEW; END IF;
 IF NEW.current_step_id IS NULL THEN RAISE EXCEPTION 'An existing production stage cannot be cleared'; END IF;
 SELECT sequence INTO STRICT next_sequence FROM public.production_steps WHERE id=NEW.current_step_id;
 SELECT name INTO customer FROM public.customers WHERE id=NEW.customer_id;
 IF TG_OP='UPDATE' AND OLD.current_step_id IS NOT NULL THEN
  SELECT sequence INTO STRICT previous_sequence FROM public.production_steps WHERE id=OLD.current_step_id;
  INSERT INTO public.process_history(order_id,spk_code,step_id,event_kind,customer_name,next_step_id,next_event_id,occurred_at)
  VALUES(NEW.id,NEW.spk_code,OLD.current_step_id,CASE WHEN next_sequence>previous_sequence THEN 'completed' ELSE 'returned' END,
   coalesce(customer,''),NEW.current_step_id,gen_random_uuid(),statement_timestamp());
 ELSE
  INSERT INTO public.process_history(order_id,spk_code,step_id,event_kind,customer_name,occurred_at)
  VALUES(NEW.id,NEW.spk_code,NEW.current_step_id,'entered',coalesce(customer,''),statement_timestamp());
 END IF;
 RETURN NEW;
END $$;

-- Imports also pass through this guard. Compatibility columns stay NULL.
CREATE OR REPLACE FUNCTION public.printex_history_no_actor() RETURNS trigger
LANGUAGE plpgsql SET search_path='' AS $$
BEGIN
 NEW.actor_id:=NULL; NEW.actor_name:=NULL; NEW.assigned_employee_id:=NULL;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.printex_history_no_actor() FROM PUBLIC,anon,authenticated;
DROP TRIGGER IF EXISTS history_no_actor ON public.process_history;
CREATE TRIGGER history_no_actor BEFORE INSERT OR UPDATE ON public.process_history
FOR EACH ROW EXECUTE FUNCTION public.printex_history_no_actor();
UPDATE public.process_history SET actor_id=NULL,actor_name=NULL,assigned_employee_id=NULL
WHERE actor_id IS NOT NULL OR actor_name IS NOT NULL OR assigned_employee_id IS NOT NULL;
DROP INDEX IF EXISTS public.process_history_actor_time;
NOTIFY pgrst,'reload schema';

-- supabase/report-migrations/0001_daily_summaries.sql
-- Derived reports only. Existing business records and histories are preserved.

CREATE TABLE IF NOT EXISTS public.report_daily_summaries (
 branch_id uuid NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
 report_date date NOT NULL, metric text NOT NULL, dimension text NOT NULL DEFAULT '',
 order_count bigint NOT NULL DEFAULT 0, meter numeric NOT NULL DEFAULT 0,
 milliseconds numeric NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(branch_id,report_date,metric,dimension)
);
CREATE INDEX IF NOT EXISTS report_daily_period ON public.report_daily_summaries(report_date,branch_id);
CREATE TABLE IF NOT EXISTS public.report_contributions (
 order_id uuid NOT NULL, branch_id uuid NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
 report_date date NOT NULL, metric text NOT NULL, dimension text NOT NULL DEFAULT '',
 meter numeric NOT NULL DEFAULT 0, milliseconds numeric NOT NULL DEFAULT 0,
 data jsonb NOT NULL DEFAULT '{}',
 PRIMARY KEY(order_id,report_date,metric,dimension)
);
CREATE INDEX IF NOT EXISTS report_contributions_period ON public.report_contributions(branch_id,metric,dimension,report_date,order_id);
CREATE INDEX IF NOT EXISTS report_contributions_all_period ON public.report_contributions(metric,dimension,report_date,order_id);
CREATE TABLE IF NOT EXISTS public.report_refresh_queue (
 order_id uuid PRIMARY KEY, branch_id uuid NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
 queued_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.report_daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_refresh_queue ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.report_daily_summaries,public.report_contributions,public.report_refresh_queue FROM anon,authenticated;

CREATE OR REPLACE FUNCTION public.printex_report_delta() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE r public.report_contributions; sign integer; BEGIN
 IF NOT EXISTS(SELECT 1 FROM public.branches WHERE id=coalesce(NEW.branch_id,OLD.branch_id)) THEN RETURN NULL; END IF;
 IF TG_OP='UPDATE' THEN
  UPDATE public.report_daily_summaries SET order_count=order_count-CASE WHEN OLD.metric='flow' THEN (OLD.data->>'visits')::bigint ELSE 1 END,meter=meter-OLD.meter,milliseconds=milliseconds-OLD.milliseconds WHERE branch_id=OLD.branch_id AND report_date=OLD.report_date AND metric=OLD.metric AND dimension=OLD.dimension;
 END IF;
 IF TG_OP='DELETE' THEN r:=OLD; sign:=-1; ELSE r:=NEW; sign:=1; END IF;
 INSERT INTO public.report_daily_summaries(branch_id,report_date,metric,dimension,order_count,meter,milliseconds)
 VALUES(r.branch_id,r.report_date,r.metric,r.dimension,sign*CASE WHEN r.metric='flow' THEN (r.data->>'visits')::bigint ELSE 1 END,sign*r.meter,sign*r.milliseconds)
 ON CONFLICT(branch_id,report_date,metric,dimension) DO UPDATE SET
 order_count=public.report_daily_summaries.order_count+excluded.order_count,
 meter=public.report_daily_summaries.meter+excluded.meter,
 milliseconds=public.report_daily_summaries.milliseconds+excluded.milliseconds,updated_at=now();
 RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS report_contribution_delta ON public.report_contributions;
CREATE TRIGGER report_contribution_delta AFTER INSERT OR UPDATE OR DELETE ON public.report_contributions FOR EACH ROW EXECUTE FUNCTION public.printex_report_delta();

CREATE OR REPLACE FUNCTION public.printex_queue_report() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE oid uuid; bid uuid; BEGIN
 IF TG_TABLE_NAME='process_history' THEN
  IF TG_OP='DELETE' THEN oid:=CASE WHEN OLD.order_identity ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN OLD.order_identity::uuid END; bid:=OLD.branch_id;
  ELSE oid:=CASE WHEN NEW.order_identity ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN NEW.order_identity::uuid END; bid:=NEW.branch_id; END IF;
 ELSE
  IF TG_OP='DELETE' THEN oid:=OLD.id; bid:=OLD.branch_id; ELSE oid:=NEW.id; bid:=NEW.branch_id; END IF;
 END IF;
 IF oid IS NOT NULL AND bid IS NOT NULL THEN
  INSERT INTO public.report_refresh_queue(order_id,branch_id) VALUES(oid,bid)
  ON CONFLICT(order_id) DO UPDATE SET branch_id=excluded.branch_id,queued_at=now();
 END IF;
 RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS orders_queue_report ON public.orders;
CREATE TRIGGER orders_queue_report AFTER INSERT OR UPDATE OR DELETE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.printex_queue_report();
DROP TRIGGER IF EXISTS history_queue_report ON public.process_history;
CREATE TRIGGER history_queue_report AFTER INSERT OR UPDATE OR DELETE ON public.process_history FOR EACH ROW EXECUTE FUNCTION public.printex_queue_report();


CREATE OR REPLACE FUNCTION public.printex_queue_customer_report() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN
 IF NEW.name IS DISTINCT FROM OLD.name THEN
  INSERT INTO public.report_refresh_queue(order_id,branch_id) SELECT id,branch_id FROM public.orders WHERE customer_id=NEW.id
  ON CONFLICT(order_id) DO UPDATE SET queued_at=now();
 END IF;
 RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS customers_queue_report ON public.customers;
CREATE TRIGGER customers_queue_report AFTER UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION public.printex_queue_customer_report();
REVOKE ALL ON FUNCTION public.printex_queue_customer_report() FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.printex_report_add(p_id uuid,p_branch uuid,p_day date,p_metric text,p_dimension text DEFAULT '',p_meter numeric DEFAULT 0,p_ms numeric DEFAULT 0,p_data jsonb DEFAULT '{}')
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path='' AS $$
 INSERT INTO public.report_contributions(order_id,branch_id,report_date,metric,dimension,meter,milliseconds,data)
 VALUES(p_id,p_branch,p_day,p_metric,p_dimension,p_meter,p_ms,p_data)
 ON CONFLICT DO NOTHING;
$$;

CREATE OR REPLACE FUNCTION public.printex_refresh_report_order(p_id uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE o public.orders; bid uuid; customer text; events jsonb; e jsonb; code text; kind text;
 stamp timestamptz; started timestamptz; completed timestamptz; last_stamp timestamptz; ending timestamptz;
 open_code text; open_at timestamptz; flow_code text; flow_at timestamptz;
 durations jsonb:='{}'; exits jsonb:='{}'; visited jsonb:='{}'; ms numeric; day date; dim text;
 payload jsonb; order_data jsonb; base jsonb; is_finished boolean; timing_code text;
BEGIN
 SELECT * INTO o FROM public.orders WHERE id=p_id;
 bid:=o.branch_id;
 IF bid IS NULL THEN SELECT branch_id INTO bid FROM public.process_history WHERE order_identity=p_id::text LIMIT 1; END IF;
 DELETE FROM public.report_contributions WHERE order_id=p_id;
 IF bid IS NULL THEN RETURN; END IF;
 SELECT name INTO customer FROM public.customers WHERE id=o.customer_id;
 order_data:=jsonb_build_object('id',o.id,'branch_id',bid,'spk_code',o.spk_code,'customer',jsonb_build_object('name',coalesce(customer,''),'phone',''),
  'production_type',o.production_type,'meter',coalesce(o.meter,0),'paper_width',o.paper_width,'customer_type',o.customer_type,
  'order_date',o.order_date,'due_at',o.due_at,'order_state',o.order_state,'photo_path',o.photo_path,
  'archive',CASE WHEN o.archived_at IS NULL THEN NULL ELSE jsonb_build_object('archivedAt',o.archived_at,'finalizedAt',o.archive_finalized_at,'deliveryMethod',o.delivery_method) END);
 SELECT coalesce(jsonb_agg(t.data ORDER BY t.stamp,(t.kind='entered')::integer,t.id),'[]') INTO events FROM (
  SELECT h.id,h.occurred_at AS stamp,h.event_kind AS kind,
   jsonb_build_object('id',h.id,'code',s.code,'kind',h.event_kind,'at',h.occurred_at,'actor',h.actor_name,'customer',h.customer_name,'spk',h.spk_code) AS data
  FROM public.process_history h JOIN public.production_steps s ON s.id=h.step_id WHERE h.order_identity=p_id::text
  UNION ALL
  SELECT h.next_event_id,h.occurred_at,'entered',
   jsonb_build_object('id',h.next_event_id,'code',s.code,'kind','entered','at',h.occurred_at,'actor',h.actor_name,'customer',h.customer_name,'spk',h.spk_code)
  FROM public.process_history h JOIN public.production_steps s ON s.id=h.next_step_id WHERE h.order_identity=p_id::text
 ) t;
 -- Original completion milestones: deduplicate before any date filtering.
 FOR e IN SELECT DISTINCT ON (value->>'code') value FROM jsonb_array_elements(events)
  WHERE value->>'kind'='completed' AND value->>'code' NOT IN ('DONE','ARCHIVE') ORDER BY value->>'code',(value->>'at')::timestamptz,value->>'id' LOOP
  code:=e->>'code'; stamp:=(e->>'at')::timestamptz; day:=(stamp AT TIME ZONE 'Asia/Jakarta')::date;
  base:=jsonb_build_object('id',e->>'id','orderId',p_id,'branchId',bid,'spkCode',e->>'spk','customerName',coalesce(e->>'customer',''),'kind','completed','orderExists',o.id IS NOT NULL,'occurredAt',stamp,'actorName',e->>'actor');
  PERFORM public.printex_report_add(p_id,bid,day,'process',code,0,0,jsonb_build_object('event',base));
  IF code='PRINTING' AND o.id IS NOT NULL THEN
   dim:=CASE WHEN upper(trim(o.production_type))='DTF' THEN 'dtf' ELSE 'sublim' END;
   PERFORM public.printex_report_add(p_id,bid,day,'output',dim,greatest(o.meter,0));
   dim:=CASE WHEN upper(trim(o.production_type))='DTF' THEN '0.6' WHEN o.paper_width IN (1.2,1.6,1.8) THEN trim(trailing '0' FROM o.paper_width::text) ELSE 'unknown' END;
   dim:=CASE WHEN dim IN ('1.2','1.6','1.8','0.6') THEN dim ELSE 'unknown' END;
   PERFORM public.printex_report_add(p_id,bid,day,'paper',dim,greatest(o.meter,0));
  END IF;
 END LOOP;
 IF o.id IS NULL THEN RETURN; END IF;
 PERFORM public.printex_report_add(p_id,bid,o.order_date,'intake','');
 IF o.order_state<>'cancelled' AND (o.order_state='completed' OR o.archive_finalized_at IS NOT NULL) THEN
  PERFORM public.printex_report_add(p_id,bid,o.order_date,'intake_completed','');
 END IF;
 IF o.archive_finalized_at IS NOT NULL THEN
  day:=(o.archive_finalized_at AT TIME ZONE 'Asia/Jakarta')::date;
  PERFORM public.printex_report_add(p_id,bid,day,'archive','',greatest(o.meter,0),0,jsonb_build_object('order',order_data));
  base:=jsonb_build_object('id','archive-completed-'||p_id,'orderId',p_id,'branchId',bid,'spkCode',o.spk_code,'customerName',coalesce(customer,''),'kind','completed','orderExists',true,'occurredAt',o.archive_finalized_at,'actorName',NULL);
  PERFORM public.printex_report_add(p_id,bid,day,'process','DONE',0,0,jsonb_build_object('event',base));
 END IF;
 SELECT min((value->>'at')::timestamptz) FILTER(WHERE value->>'kind'='entered' AND value->>'code' IN ('DESIGN','DESIGN_DONE')),
  min((value->>'at')::timestamptz) FILTER(WHERE value->>'kind'='entered' AND value->>'code'='DONE'),max((value->>'at')::timestamptz)
 INTO started,completed,last_stamp FROM jsonb_array_elements(events);
 is_finished:=completed IS NOT NULL OR (SELECT production_steps.code IN ('DONE','ARCHIVE') FROM public.production_steps WHERE id=o.current_step_id);
 ending:=coalesce(completed,last_stamp);
 FOR e IN SELECT value FROM jsonb_array_elements(events) LOOP
  code:=e->>'code'; kind:=e->>'kind'; stamp:=(e->>'at')::timestamptz;
  -- Flow averages retain all actual visits; returns are not completions.
  IF flow_code IS NOT NULL AND (kind='entered' OR flow_code=code) AND NOT(kind='entered' AND flow_code=code) THEN
   IF kind='completed' OR (kind='entered' AND (SELECT sequence FROM public.production_steps WHERE production_steps.code=e->>'code')>(SELECT sequence FROM public.production_steps WHERE production_steps.code=flow_code)) THEN
    day:=(stamp AT TIME ZONE 'Asia/Jakarta')::date;
    -- Collapse visit sums into one contribution per order/day/stage below.
    INSERT INTO public.report_contributions(order_id,branch_id,report_date,metric,dimension,milliseconds,data)
    VALUES(p_id,bid,day,'flow',flow_code,greatest(extract(epoch FROM stamp-flow_at)*1000,0),jsonb_build_object('visits',1))
    ON CONFLICT(order_id,report_date,metric,dimension) DO UPDATE SET milliseconds=public.report_contributions.milliseconds+excluded.milliseconds,data=jsonb_build_object('visits',(public.report_contributions.data->>'visits')::integer+1);
   END IF;
   flow_code:=NULL;
  END IF;
  IF kind='entered' AND flow_code IS DISTINCT FROM code THEN flow_code:=code; flow_at:=stamp; END IF;
  IF started IS NULL OR stamp<started OR stamp>ending THEN CONTINUE; END IF;
  IF (kind<>'entered' AND open_code=code) OR (kind='entered' AND open_code IS NOT NULL AND open_code IS DISTINCT FROM code) THEN
   ms:=greatest(extract(epoch FROM least(stamp,ending)-open_at)*1000,0);
   durations:=jsonb_set(durations,ARRAY[open_code],to_jsonb(coalesce((durations->>open_code)::numeric,0)+ms));
   exits:=jsonb_set(exits,ARRAY[open_code],to_jsonb(least(stamp,ending))); open_code:=NULL;
  END IF;
  IF kind='entered' AND code IN ('DESIGN','DESIGN_DONE','PRINTING','PRESS') AND open_code IS DISTINCT FROM code THEN
   open_code:=code; open_at:=stamp; visited:=jsonb_set(visited,ARRAY[code],'true');
  END IF;
 END LOOP;
 IF open_code IS NOT NULL AND is_finished THEN
  durations:=jsonb_set(durations,ARRAY[open_code],to_jsonb(coalesce((durations->>open_code)::numeric,0)+greatest(extract(epoch FROM ending-open_at)*1000,0)));
  IF completed IS NOT NULL THEN exits:=jsonb_set(exits,ARRAY[open_code],to_jsonb(completed)); END IF;
 END IF;
 payload:=jsonb_build_object('order',order_data,'productionMilliseconds',CASE WHEN started IS NOT NULL AND completed IS NOT NULL THEN greatest(extract(epoch FROM completed-started)*1000,0) END);
 IF started IS NOT NULL AND completed IS NOT NULL THEN
  day:=(completed AT TIME ZONE 'Asia/Jakarta')::date;
  PERFORM public.printex_report_add(p_id,bid,day,'production','',0,greatest(extract(epoch FROM completed-started)*1000,0),payload);
 END IF;
 FOREACH timing_code IN ARRAY ARRAY['DESIGN','DESIGN_DONE','PRINTING','PRESS'] LOOP
  IF visited ? timing_code AND exits ? timing_code AND NOT(coalesce(NOT is_finished AND open_code=timing_code,false)) THEN
   day:=((exits->>timing_code)::timestamptz AT TIME ZONE 'Asia/Jakarta')::date; ms:=coalesce((durations->>timing_code)::numeric,0);
   PERFORM public.printex_report_add(p_id,bid,day,'timing',timing_code,0,ms,payload);
   IF timing_code IN ('PRINTING','PRESS') THEN
    dim:=CASE WHEN timing_code='PRESS' THEN 'press' WHEN upper(trim(o.production_type))='DTF' THEN 'dtf' ELSE 'sublim' END;
    PERFORM public.printex_report_add(p_id,bid,day,'productivity',dim||':'||CASE WHEN upper(trim(o.production_type))='DTF' THEN 'dtf' ELSE coalesce((o.paper_width::float8)::text,'unknown') END,greatest(o.meter,0),ms);
   END IF;
  END IF;
 END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.printex_refresh_report_queue(p_limit integer DEFAULT 100) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE r record; refreshed integer:=0; BEGIN
 IF NOT pg_try_advisory_xact_lock(73621,1) THEN RETURN -1; END IF;
 FOR r IN SELECT order_id FROM public.report_refresh_queue ORDER BY queued_at,order_id LIMIT least(greatest(p_limit,1),500) FOR UPDATE SKIP LOCKED LOOP
  PERFORM public.printex_refresh_report_order(r.order_id);
  DELETE FROM public.report_refresh_queue WHERE order_id=r.order_id; refreshed:=refreshed+1;
 END LOOP;
 RETURN refreshed;
END $$;

CREATE OR REPLACE FUNCTION public.printex_daily_report(p_start date,p_end date,p_branch uuid DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE r record; pending boolean; result jsonb; allowed uuid[]; BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 SELECT array_agg(id) INTO allowed FROM public.printex_read_branches() AS id;
 IF p_start IS NULL OR p_end IS NULL OR p_end<p_start OR p_end-p_start>365 THEN RAISE EXCEPTION 'Rentang laporan tidak valid'; END IF;
 IF pg_try_advisory_xact_lock(73621,1) THEN
 FOR r IN SELECT order_id FROM public.report_refresh_queue WHERE branch_id=ANY(allowed)
  AND (p_branch IS NULL OR branch_id=p_branch) ORDER BY queued_at,order_id LIMIT 100 FOR UPDATE SKIP LOCKED LOOP
  PERFORM public.printex_refresh_report_order(r.order_id); DELETE FROM public.report_refresh_queue WHERE order_id=r.order_id;
 END LOOP;
 END IF;
 SELECT exists(SELECT 1 FROM public.report_refresh_queue WHERE branch_id=ANY(allowed) AND (p_branch IS NULL OR branch_id=p_branch)) INTO pending;
 SELECT coalesce(jsonb_agg(jsonb_build_object('day',report_date,'branchId',branch_id,'metric',metric,'dimension',dimension,'count',order_count,'meter',meter,'milliseconds',milliseconds) ORDER BY report_date,branch_id,metric,dimension),'[]') INTO result
 FROM public.report_daily_summaries WHERE report_date BETWEEN p_start AND p_end AND order_count>0
 AND branch_id=ANY(allowed) AND (p_branch IS NULL OR branch_id=p_branch);
 RETURN jsonb_build_object('rows',result,'pending',pending,'asOf',now());
END $$;
CREATE OR REPLACE FUNCTION public.printex_report_details(p_start date,p_end date,p_metric text,p_dimension text DEFAULT '',p_branch uuid DEFAULT NULL,p_offset integer DEFAULT 0,p_limit integer DEFAULT 50,p_search text DEFAULT '') RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE result jsonb; total bigint; allowed uuid[]; BEGIN
 IF NOT public.printex_staff() THEN RAISE EXCEPTION 'Akun belum aktif' USING ERRCODE='42501'; END IF;
 SELECT array_agg(id) INTO allowed FROM public.printex_read_branches() AS id;
 IF p_start IS NULL OR p_end IS NULL OR p_end<p_start OR p_end-p_start>365 OR p_metric IS NULL OR p_metric NOT IN ('archive','process','timing','production') OR p_offset IS NULL OR p_offset<0 THEN RAISE EXCEPTION 'Filter laporan tidak valid'; END IF;
 SELECT count(*) INTO total FROM public.report_contributions WHERE report_date BETWEEN p_start AND p_end AND metric=p_metric AND dimension=p_dimension
 AND branch_id=ANY(allowed) AND (p_branch IS NULL OR branch_id=p_branch) AND (p_search='' OR position(lower(p_search) IN lower(coalesce(data->'order'->>'spk_code',data->'event'->>'spkCode','')||' '||coalesce(data->'order'->'customer'->>'name',data->'event'->>'customerName','')))>0);
 SELECT coalesce(jsonb_agg(t.data),'[]') INTO result FROM (SELECT data||jsonb_build_object('milliseconds',milliseconds,'day',report_date) AS data FROM public.report_contributions
 WHERE report_date BETWEEN p_start AND p_end AND metric=p_metric AND dimension=p_dimension AND branch_id=ANY(allowed)
 AND (p_branch IS NULL OR branch_id=p_branch) AND (p_search='' OR position(lower(p_search) IN lower(coalesce(data->'order'->>'spk_code',data->'event'->>'spkCode','')||' '||coalesce(data->'order'->'customer'->>'name',data->'event'->>'customerName','')))>0)
 ORDER BY report_date DESC,order_id LIMIT least(greatest(p_limit,1),200) OFFSET p_offset) t;
 RETURN jsonb_build_object('items',result,'total',total);
END $$;
REVOKE ALL ON FUNCTION public.printex_report_delta(),public.printex_queue_report(),public.printex_report_add(uuid,uuid,date,text,text,numeric,numeric,jsonb),public.printex_refresh_report_order(uuid),public.printex_refresh_report_queue(integer),public.printex_daily_report(date,date,uuid),public.printex_report_details(date,date,text,text,uuid,integer,integer,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.printex_daily_report(date,date,uuid),public.printex_report_details(date,date,text,text,uuid,integer,integer,text) TO authenticated;
INSERT INTO public.report_refresh_queue(order_id,branch_id) SELECT id,branch_id FROM public.orders o WHERE NOT EXISTS(SELECT 1 FROM public.report_contributions c WHERE c.order_id=o.id AND c.metric='intake') ON CONFLICT DO NOTHING;
-- Include retained reports whose orders were deleted.
INSERT INTO public.report_refresh_queue(order_id,branch_id) SELECT DISTINCT order_identity::uuid,branch_id FROM public.process_history WHERE branch_id IS NOT NULL AND order_identity ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND NOT EXISTS(SELECT 1 FROM public.report_contributions c WHERE c.order_id=process_history.order_identity::uuid) ON CONFLICT DO NOTHING;
DO $$ DECLARE definition text; BEGIN
 SELECT pg_get_functiondef('public.printex_online_status()'::regprocedure) INTO definition;
 IF position('daily_summaries_enabled' IN definition)=0 THEN EXECUTE replace(definition,'''schema_version'',','''daily_summaries_enabled'',true,''schema_version'','); END IF;
 IF to_regnamespace('cron') IS NOT NULL THEN
  EXECUTE 'SELECT cron.schedule(''printex-daily-report-refresh'',''* * * * *'',''SELECT public.printex_refresh_report_queue(500);'')';
 END IF;
END $$;
NOTIFY pgrst,'reload schema';

-- supabase/report-migrations/0002_compact_payloads.sql
-- Store the report snapshot once per order. RPC JSON remains compatible.

CREATE TABLE IF NOT EXISTS public.report_order_payloads (
 order_id uuid PRIMARY KEY,
 branch_id uuid NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
 data jsonb NOT NULL
);
ALTER TABLE public.report_order_payloads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.report_order_payloads FROM PUBLIC,anon,authenticated;

DO $$ BEGIN
 IF EXISTS(SELECT order_id FROM public.report_contributions
  WHERE data ? 'order' AND data->'order'<>'null'::jsonb
  GROUP BY order_id HAVING count(DISTINCT data->'order')>1) THEN
  RAISE EXCEPTION 'Conflicting report snapshots: refusing to merge';
 END IF;
END $$;
INSERT INTO public.report_order_payloads(order_id,branch_id,data)
SELECT DISTINCT ON(order_id) order_id,branch_id,data->'order'
FROM public.report_contributions WHERE data ? 'order' AND data->'order'<>'null'::jsonb
ORDER BY order_id
ON CONFLICT(order_id) DO UPDATE SET branch_id=excluded.branch_id,data=excluded.data;

CREATE OR REPLACE FUNCTION public.printex_compact_report_payload() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NEW.data ? 'order' AND NEW.data->'order'<>'null'::jsonb THEN
  INSERT INTO public.report_order_payloads(order_id,branch_id,data)
  VALUES(NEW.order_id,NEW.branch_id,NEW.data->'order')
  ON CONFLICT(order_id) DO UPDATE SET branch_id=excluded.branch_id,data=excluded.data
  WHERE (public.report_order_payloads.branch_id,public.report_order_payloads.data)
   IS DISTINCT FROM (excluded.branch_id,excluded.data);
  NEW.data:=jsonb_set(NEW.data,'{order}','null'::jsonb);
 END IF;
 IF NEW.data ? 'event' THEN
  NEW.data:=jsonb_set(NEW.data,'{event,actorName}','null'::jsonb);
 END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.printex_compact_report_payload() FROM PUBLIC,anon,authenticated;
DROP TRIGGER IF EXISTS report_compact_payload ON public.report_contributions;
CREATE TRIGGER report_compact_payload BEFORE INSERT OR UPDATE ON public.report_contributions
FOR EACH ROW EXECUTE FUNCTION public.printex_compact_report_payload();

-- Payload-only changes cannot affect aggregate values. Avoid delta churn.
ALTER TABLE public.report_contributions DISABLE TRIGGER report_contribution_delta;
UPDATE public.report_contributions SET data=CASE WHEN data ? 'order'
 THEN jsonb_set(data,'{order}','null'::jsonb) ELSE data END
WHERE (data ? 'order' AND data->'order'<>'null'::jsonb)
 OR (data ? 'event' AND data->'event'->'actorName' IS DISTINCT FROM 'null'::jsonb);
ALTER TABLE public.report_contributions ENABLE TRIGGER report_contribution_delta;

CREATE OR REPLACE VIEW public.printex_report_expanded AS
SELECT c.order_id,c.branch_id,c.report_date,c.metric,c.dimension,c.meter,c.milliseconds,
 CASE WHEN c.data ? 'order' AND p.order_id IS NOT NULL THEN jsonb_set(c.data,'{order}',p.data) ELSE c.data END AS data
FROM public.report_contributions c LEFT JOIN public.report_order_payloads p ON p.order_id=c.order_id AND p.branch_id=c.branch_id;
REVOKE ALL ON public.printex_report_expanded FROM PUBLIC,anon,authenticated;
DO $$ DECLARE definition text; BEGIN
 SELECT pg_get_functiondef('public.printex_report_details(date,date,text,text,uuid,integer,integer,text)'::regprocedure) INTO definition;
 definition:=replace(definition,'FROM public.report_contributions','FROM public.printex_report_expanded');
 EXECUTE definition;
  SELECT pg_get_functiondef('public.printex_refresh_report_order(uuid)'::regprocedure) INTO definition;
  definition:=replace(definition,'''actor'',h.actor_name','''actor'',NULL');
 IF position('DELETE FROM public.report_order_payloads WHERE order_id=p_id;' IN definition)=0 THEN
  definition:=replace(definition,'DELETE FROM public.report_contributions WHERE order_id=p_id;',
   'DELETE FROM public.report_contributions WHERE order_id=p_id; DELETE FROM public.report_order_payloads WHERE order_id=p_id;');
 END IF;
  EXECUTE definition;
END $$;
DELETE FROM public.report_order_payloads p WHERE NOT EXISTS(
 SELECT 1 FROM public.report_contributions c WHERE c.order_id=p.order_id AND c.data ? 'order'
);
NOTIFY pgrst,'reload schema';

-- supabase/report-migrations/0003_report_read_indexes.sql
-- Match queue draining and report pagination order. No business rows are modified.

CREATE INDEX IF NOT EXISTS report_queue_oldest ON public.report_refresh_queue(queued_at,order_id);
CREATE INDEX IF NOT EXISTS report_queue_branch_oldest ON public.report_refresh_queue(branch_id,queued_at,order_id);
CREATE INDEX IF NOT EXISTS report_details_branch_page ON public.report_contributions(branch_id,metric,dimension,report_date DESC,order_id);
CREATE INDEX IF NOT EXISTS report_details_all_page ON public.report_contributions(metric,dimension,report_date DESC,order_id);

COMMIT;
