'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Archive, ArrowLeft, Search } from 'lucide-react'
import { useAllOrders } from '@/lib/production-board'
import { jakartaDate } from '@/lib/process-metrics'

export default function ArchivesPage() {
  const orders = useAllOrders().filter(order => order.board_stage === 'archive' && order.archive?.finalizedAt)
  const [query, setQuery] = useState('')
  const [date, setDate] = useState('')
  const filtered = orders.filter(order => (!query.trim() || `${order.spk_code} ${order.customer.name}`.toLowerCase().includes(query.trim().toLowerCase())) && (!date || (order.archive && jakartaDate(order.archive.finalizedAt!) === date))).sort((a, b) => (b.archive?.finalizedAt ?? '').localeCompare(a.archive?.finalizedAt ?? ''))
  return <div className="mx-auto max-w-7xl space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-bold text-slate-900"><Archive className="h-6 w-6 text-blue-600" /> Laporan Arsip</h2><p className="mt-1 text-sm text-slate-500">Order yang diselesaikan dari board Arsip. Tanggal laporan mengikuti saat tombol Selesai ditekan.</p></div><Link href="/schedule" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm text-slate-600"><ArrowLeft className="h-4 w-4" /> Board Produksi</Link></div>
    <div className="grid gap-4 sm:grid-cols-3">{[{ label: 'Total selesai dari arsip', value: orders.length }, { label: 'Diambil pembeli', value: orders.filter(order => order.archive?.deliveryMethod === 'pickup').length }, { label: 'Sudah dikirim', value: orders.filter(order => order.archive?.deliveryMethod === 'delivery').length }].map(item => <section key={item.label} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{item.label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{item.value}</p></section>)}</div>
    <div className="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4"><label className="min-w-56 flex-1 text-xs font-medium text-slate-500">Cari order<div className="relative mt-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Kode SPK atau nama customer" className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm text-slate-900" /></div></label><label className="text-xs font-medium text-slate-500">Tanggal klik Selesai (WIB)<input type="date" value={date} onChange={event => setDate(event.target.value)} className="mt-2 block rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900" /></label>{(date || query) && <button onClick={() => { setDate(''); setQuery('') }} className="px-3 py-2.5 text-sm text-blue-600">Reset filter</button>}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4 text-sm text-slate-500">{filtered.length} order ditemukan</div><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['Order', 'Customer', 'Produksi', 'Tanggal order', 'Selesai dari arsip (WIB)', 'Penyerahan', 'Detail'].map(title => <th key={title} className="px-4 py-3 font-medium">{title}</th>)}</tr></thead><tbody>{filtered.map(order => <tr key={order.id} className="border-t border-slate-100 text-slate-600"><td className="px-4 py-4 font-semibold text-slate-900">{order.spk_code}</td><td className="px-4 py-4">{order.customer.name}</td><td className="px-4 py-4">{order.production_type} · {order.meter} m</td><td className="px-4 py-4">{order.order_date}</td><td className="px-4 py-4">{order.archive ? new Date(order.archive.finalizedAt!).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' }) : 'Belum tercatat'}</td><td className="px-4 py-4"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-600">{order.archive?.deliveryMethod === 'pickup' ? 'Diambil pembeli' : order.archive?.deliveryMethod === 'delivery' ? 'Sudah dikirim' : 'Arsip lama'}</span></td><td className="px-4 py-4"><Link href={`/orders/${order.id}`} className="font-medium text-blue-600">Lihat order</Link></td></tr>)}{!filtered.length && <tr><td colSpan={7} className="px-4 py-14 text-center text-slate-400">{date || query ? 'Tidak ada arsip yang cocok dengan filter.' : 'Belum ada laporan. Klik Selesai pada kartu di kolom Arsip untuk menyimpan laporan.'}</td></tr>}</tbody></table></div></section>
    <p className="text-xs leading-5 text-slate-500">Laporan proses order yang diarsipkan tetap tersedia di <Link href="/reports" className="font-medium text-blue-600">Laporan Proses</Link>. Arsip tersimpan di browser ini; penyimpanan bersama antarperangkat belum terhubung.</p>
  </div>
}
